# -*- coding: utf-8 -*-
"""470 LCC Project Infrastructure

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BSR9yGKtA4pFdek-2fFbDys2nBLIdR3H

# Drive Mounting
"""

import os
from google.colab import drive
drive.mount('/content/drive')

shared_drive_name = "Sonoma Landcover Classification Project"

shared_drive_path = f"/content/drive/Shared drives/{shared_drive_name}"

subdirs = [
    "data/raw",
    "data/processed",
    "notebooks",
    "models",
    "exports",
    "figures"
]

for sub in subdirs:
    path = os.path.join(shared_drive_path, sub)
    os.makedirs(path, exist_ok=True)

print(f"Project directories ready under:\n{shared_drive_path}")
!ls -R "$shared_drive_path"

"""# Imports & Dependencies



"""

# --- Install dependencies ---
!pip install geopandas shapely fiona pyproj rasterio rtree folium scikit-learn earthengine-api tqdm

import ee

ee.Authenticate()
ee.Initialize(project='sonoma-lcc')

import os
import geopandas as gpd, rasterio
import pandas as pd
import numpy as np
from shapely.validation import make_valid
import rasterio
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import folium
from tqdm import tqdm
import geopandas as gpd
from shapely.geometry import box
import datetime as dt
from tqdm.auto import tqdm, trange
import time
import re
from pathlib import Path
from rasterio.warp import reproject
from rasterio.enums import Resampling as RS
import pyarrow as pa, pyarrow.parquet as pq
from pyproj import Transformer, CRS

workspace = "/content/drive/Shared drives/Sonoma Landcover Classification Project/workspace"

# Create the folder (and parent dirs if missing)
os.makedirs(workspace, exist_ok=True)

# Move into it
os.chdir(workspace)

print("Workspace directory is ready and set to:", os.getcwd())

workspace = "/content/drive/Shared drives/Sonoma Landcover Classification Project/workspace"
os.chdir(workspace)
print("Working directory:", os.getcwd())

"""# Tile Generation Code

"""

# CONFIG
PROJECT     = 'sonoma-lcc'
SHAPE_ASSET = 'projects/sonoma-lcc/assets/sonoma_wgs84' # SET SHAPEFILE HERE
LABEL_PROP  = 'LIFEFORM'
YEAR        = 2024 # Whatever year you're pulling

FORCE_UTM   = False          # False = fastest, True = EE reprojects to UTM@10m
CRS         = 'EPSG:32610'
SCALE       = 10

# Sonoma bounding box derived from existing parquets
XMIN = -123.709561
XMAX = -122.170186
YMIN = 38.018977
YMAX = 38.980797

# Tile size (bigger tiles -> fewer tasks, less EE struggle)
DEG_LON = 0.16
DEG_LAT = 0.16

# Drive output folders
DRIVE_FOLDER_EMB = f"sonoma10m_emb_{YEAR}"
DRIVE_FOLDER_LAB = f"sonoma10m_lab_{YEAR}"
FNPREFIX_EMB     = "emb_tile_"
FNPREFIX_LAB     = "lab_tile_"

def make_tiles(xmin, xmax, ymin, ymax, dlon, dlat):
    rects = []
    x = xmin
    while x < xmax:
        x1 = min(x + dlon, xmax)
        y = ymin
        while y < ymax:
            y1 = min(y + dlat, ymax)
            rects.append(ee.Geometry.Rectangle([x, y, x1, y1], None, False))
            y += dlat
        x += dlon
    return rects

tiles = make_tiles(XMIN, XMAX, YMIN, YMAX, DEG_LON, DEG_LAT)
print("Tile count:", len(tiles))

# Labels FC
fc0 = ee.FeatureCollection(SHAPE_ASSET)

# Build LUT label
keys = (fc0.aggregate_array(LABEL_PROP)
          .map(lambda v: ee.String(v))
          .distinct()
          .sort())
vals = ee.List.sequence(1, keys.size())
lut  = ee.Dictionary.fromLists(keys, vals)

fc = fc0.map(
    lambda f: f.set(
        'label_code',
        ee.Number(
            ee.Algorithms.If(
                keys.contains(ee.String(f.get(LABEL_PROP))),
                lut.get(ee.String(f.get(LABEL_PROP))),
                0
            )
        )
    )
)

RUN = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
print("RUN tag:", RUN)
print("Label codes:", keys.getInfo())

# Labels
fc = ee.FeatureCollection(SHAPE_ASSET)

# Turns polygon label strings into numeric codes so Image.paint works

# Load original
fc0 = ee.FeatureCollection(SHAPE_ASSET)

# Distinct label strings (server-side)
keys = (fc0.aggregate_array(LABEL_PROP)
          .map(lambda v: ee.String(v))
          .distinct()
          .sort())

vals = ee.List.sequence(1, keys.size())

# LUT dictionary
lut = ee.Dictionary.fromLists(keys, vals)

# Adds numeric 'label_code' field to every feature
fc = fc0.map(
    lambda f: f.set(
        'label_code',
        ee.Number(
            ee.Algorithms.If(
                keys.contains(ee.String(f.get(LABEL_PROP))),
                lut.get(ee.String(f.get(LABEL_PROP))),
                0
            )
        )
    )
)

# Load Sonoma geometry
sonoma_geom = ee.FeatureCollection(SHAPE_ASSET).geometry()

def get_embeddings_for_tile(tile_geom):
    start = ee.Date.fromYMD(YEAR, 1, 1)
    end   = start.advance(1, 'year')

    col = (ee.ImageCollection('GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL')
             .filterDate(start, end)
             .filterBounds(tile_geom))

    img = col.mosaic().clip(tile_geom)

    if FORCE_UTM:
        img = img.reproject(crs=CRS, scale=SCALE)  # CRS='EPSG:32610', SCALE=10

    return img

import time
from tqdm import tqdm

def _drive_params(prefix, idx, region):
    p = dict(
        description   = f"{prefix}_tile_{idx}",
        folder        = (DRIVE_FOLDER_EMB if prefix == "emb" else DRIVE_FOLDER_LAB),
        fileNamePrefix= f"{prefix}_tile_{idx}",
        region        = region,
        maxPixels     = 1e13,
        fileFormat    = "GeoTIFF",
    )
    if FORCE_UTM:
        p.update(dict(crs=CRS, scale=SCALE))
    return p

FORCE_UTM = True
CRS       = "EPSG:32610"
SCALE     = 10

def export_embeddings_tile(idx, geom):
    img = get_embeddings_for_tile(geom)

    task = ee.batch.Export.image.toDrive(
        image=img,
        description=f"{FNPREFIX_EMB}{idx}_{RUN}",
        folder=DRIVE_FOLDER_EMB,
        fileNamePrefix=f"{FNPREFIX_EMB}{idx}",
        region=geom,
        scale=SCALE,           # 10
        maxPixels=1e13,
        fileFormat="GeoTIFF",
        **({"crs": CRS} if FORCE_UTM else {})
    )
    task.start()
    return task


def export_labels_tile(idx, geom):
    fc_tile = fc.filterBounds(geom)

    labelImg = (
        ee.Image()
        .paint(fc_tile, 'label_code')
        .rename('label')
        .unmask(0)
        .toInt16()
        .clip(geom)
    )

    params = _drive_params("lab", idx, geom)

    task = ee.batch.Export.image.toDrive(
        image = labelImg,
        **params
    )
    task.start()
    return task

def summarize(tasks, n=8):
    from collections import Counter
    sts = [t.status().get('state') for t in tasks]
    print(Counter(sts))
    for t in tasks[:n]:
        st = t.status()
        print(st.get('state'), st.get('description'), st.get('error_message'))

col_year = (ee.ImageCollection('GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL')
              .filter(ee.Filter.calendarRange(YEAR, YEAR, 'year')))

print("images in year:", col_year.size().getInfo())  # expect ~1e4

def debug_tile(i):
    g = tiles[i]
    start = ee.Date.fromYMD(YEAR, 1, 1)
    end   = start.advance(1, 'year')

    col = (ee.ImageCollection('GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL')
             .filterDate(start, end)
             .filterBounds(g))

    print("tile", i, "n_imgs:", col.size().getInfo())

    img = col.mosaic().clip(g)
    print("bands:", img.bandNames().size().getInfo())
    print("first bands:", img.bandNames().slice(0, 5).getInfo())

IC = ee.ImageCollection('GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL')

def get_tile_embedding(idx):
    geom  = tiles[idx]
    start = ee.Date.fromYMD(YEAR, 1, 1)
    end   = start.advance(1, 'year')

    col = (IC
           .filterDate(start, end)
           .filterBounds(geom))

    img = col.mosaic().clip(geom)

    if FORCE_UTM:
        img = img.reproject(crs=CRS, scale=SCALE)

    return img, col

def debug_embeddings_tile(idx, n_samples=10):
    geom = tiles[idx]
    img, col = get_tile_embedding(idx)

    n_imgs   = col.size().getInfo()
    bandlist = img.bandNames()
    n_bands  = bandlist.size().getInfo()

    print(f"Tile {idx}")
    print("  n_imgs   :", n_imgs)
    print("  n_bands  :", n_bands)
    if n_bands > 0:
        print("  first 5 bands:", bandlist.slice(0, 5).getInfo())

    # Sample a few pixels inside this tile
    if n_bands > 0:
        pts = (img
               .sample(region=geom,
                       scale=SCALE,
                       numPixels=n_samples,
                       seed=0,
                       geometries=True))
        n_pts = pts.size().getInfo()
        print("  sample pixels:", n_pts)
        if n_pts > 0:
            print("  first sample:", pts.first().getInfo())
    else:
        print("  (no bands – this tile likely has no embedding coverage.)")

import folium
import ee

# Visualizes tile placement before tile generation

fc_tiles = ee.FeatureCollection([
    ee.Feature(geom, {"id": i}) for i, geom in enumerate(tiles)
])

grid_center = fc_tiles.geometry().centroid(10).coordinates().getInfo()

m = folium.Map(location=[grid_center[1], grid_center[0]], zoom_start=9)

# Convert the FeatureCollection to GeoJSON client-side
tiles_geojson = fc_tiles.getInfo()

# Add all tiles as a single GeoJson layer
folium.GeoJson(
    tiles_geojson,
    name="tiles",
    style_function=lambda feature: {
        "fillOpacity": 0,
        "color": "red",
        "weight": 1,
    },
    tooltip=folium.GeoJsonTooltip(
        fields=["id"],
        aliases=["Tile ID"],
    ),
).add_to(m)

folium.LayerControl().add_to(m)
m

#Print band names to test embedding data presence
img = get_embeddings_for_tile(tiles[15])
print(img.bandNames().getInfo())

def safe_start(tasks):
    for t in tasks:
        try:
            t.start()
        except Exception as e:
            msg = str(e)
            if "already started with the given request_id" in msg:
                # Ignore – it’s already in the queue
                pass
            else:
                raise

import time
from tqdm import tqdm

def run_batched(build_fn, indices, batch=10, poll=15, backoff=20, tag=""):
    # slightly smaller batch + longer poll to be gentle
    for s in range(0, len(indices), batch):
        chunk_idx = indices[s:s+batch]
        tasks = [build_fn(i, tiles[i]) for i in chunk_idx]
        with tqdm(total=len(tasks), desc=f"{tag} {s}-{s+len(indices)-1}") as pbar:
            done = 0
            while done < len(tasks):
                time.sleep(poll)
                done = sum(t.status().get('state') in ('COMPLETED','FAILED','CANCELLED')
                           for t in tasks)
                pbar.n = done
                pbar.refresh()
        time.sleep(backoff)

all_idx = list(range(len(tiles)))

# First: embeddings
run_batched(export_embeddings_tile, all_idx, batch=10, poll=15, backoff=20, tag="emb")

# Then: labels
#run_batched(export_labels_tile,     all_idx, batch=10, poll=15, backoff=20, tag="lab")

"""# Parquet Generation Code

"""

!pip -q install rasterio pyarrow pyproj tqdm

# COMBINATION CODE - COMBINES EMB AND LAB TO PARQUET. SET DIRECTORIES HERE
EMB_DIR = Path("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/emb_tiles_2017")
LAB_DIR = Path("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/lab_tiles_2017")
OUT_DIR = Path("/content/parquet_sonoma10m_2017"); OUT_DIR.mkdir(parents=True, exist_ok=True)

assert EMB_DIR.is_dir(), f"Missing {EMB_DIR}"
assert LAB_DIR.is_dir(), f"Missing {LAB_DIR}"

idx_pat = re.compile(r'.*_(\d+)\.tif$', re.IGNORECASE)

def idx_of(p: Path):
    m = idx_pat.match(p.name)
    return int(m.group(1)) if m else None

emb_files = {idx_of(p): p for p in EMB_DIR.glob("*.tif") if idx_of(p) is not None}
lab_files = {idx_of(p): p for p in LAB_DIR.glob("*.tif") if idx_of(p) is not None}

common_idx = sorted(set(emb_files).intersection(lab_files))
print(f"Found {len(common_idx)} matching tile pairs.")
print(common_idx)
if not common_idx:
    raise SystemExit("No matching indices between emb_tiles and lab_tiles.")

CRS_STR = 'EPSG:32610'

from pyproj import CRS as PJ_CRS, Transformer

# crs might be a rasterio CRS object, a string, or None
def to_wgs84_transformer(crs_obj_or_str):
    src = PJ_CRS.from_user_input(crs_obj_or_str or CRS_STR)
    dst = PJ_CRS.from_epsg(4326)
    return Transformer.from_crs(src, dst, always_xy=True)

def ensure_alignment(emb_ds, lab_ds):
    """Return (E64, Lab, transform, crs) with embeddings aligned to label grid."""
    Lab = lab_ds.read(1)
    H, W = Lab.shape
    dst_transform, dst_crs = lab_ds.transform, lab_ds.crs

    same_grid = (
        emb_ds.crs == dst_crs and
        emb_ds.transform == dst_transform and
        emb_ds.width == W and emb_ds.height == H
    )

    bands = min(64, emb_ds.count)
    if same_grid:
        E = emb_ds.read(indexes=list(range(1, bands+1))).astype(np.float32)
        return E, Lab, dst_transform, dst_crs

    # Reproject embeddings → label grid
    E = np.empty((bands, H, W), dtype=np.float32)
    for b in range(bands):
        src = emb_ds.read(b+1).astype(np.float32, copy=False)
        dst = np.empty((H, W), dtype=np.float32)
        reproject(
            source=src,
            destination=dst,
            src_transform=emb_ds.transform,
            src_crs=emb_ds.crs,
            dst_transform=dst_transform,
            dst_crs=dst_crs,
            resampling=RS.bilinear,
            num_threads=2
        )
        E[b] = dst
    return E, Lab, dst_transform, dst_crs

def write_parquet_for_pair(idx, emb_path: Path, lab_path: Path, drop_unlabeled=False):
    with rasterio.open(emb_path) as E, rasterio.open(lab_path) as L:
        E64, Lab, transform, crs = ensure_alignment(E, L)  # E64: (bands, H, W)
        bands = E64.shape[0]
        if bands < 1:
            raise RuntimeError(f"No bands in {emb_path.name}")

        H, W = Lab.shape
        A = E64.reshape(bands, -1).T  # (N, bands)
        y_vec = Lab.reshape(-1).astype(np.int32)

        if drop_unlabeled:
            mask = (y_vec != 0)
            A, y_vec = A[mask], y_vec[mask]
            keep = np.where(mask)[0]
        else:
            keep = np.arange(H*W)

        rows = (keep // W).astype(np.int32)
        cols = (keep %  W).astype(np.int32)

        xs, ys = rasterio.transform.xy(transform, rows, cols, offset='center')
        xs = np.asarray(xs, dtype=np.float64)
        ys = np.asarray(ys, dtype=np.float64)

        # coords → WGS84
        to_wgs84 = to_wgs84_transformer(crs)   # where `crs` came from the raster/array
        lons, lats = to_wgs84.transform(xs, ys)

        cell_id = (cols.astype(np.int64) << 32) | rows.astype(np.int64)

        names = ["cell_id","i","j","x","y","lon","lat","label"] + [f"A{k:02d}" for k in range(bands)]
        arrays = [
            pa.array(cell_id),
            pa.array(rows), pa.array(cols),
            pa.array(xs), pa.array(ys),
            pa.array(lons), pa.array(lats),
            pa.array(y_vec)
        ] + [pa.array(A[:,k]) for k in range(bands)]

        tbl = pa.Table.from_arrays(arrays, names=names)
        out_path = OUT_DIR / f"tile_{idx:04d}.parquet"
        pq.write_table(tbl, out_path, compression="zstd", version="2.6", data_page_version="2.0")
        return out_path

written = []
for idx in tqdm(common_idx, desc="DriveParquet tiles"):
    p = write_parquet_for_pair(idx, emb_files[idx], lab_files[idx], drop_unlabeled=False)
    written.append(str(p))
print(f"Wrote {len(written)} parquet files to {OUT_DIR}")

# Point to the parquet tiles in Shared Drive for basic checks
from pathlib import Path
import glob, pyarrow.parquet as pq

PARQUET_DIR = Path("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_new")
assert PARQUET_DIR.is_dir(), f"Missing directory: {PARQUET_DIR}"

files = sorted(glob.glob(str(PARQUET_DIR / "*.parquet")))
print(f"Found {len(files)} parquet tiles in:\n  {PARQUET_DIR}")

# Show schema of the first tile
t0 = pq.read_table(files[0])
print(t0.schema)z
print(t0.num_rows, "rows in", files[0])

# Ensure all tiles share the same columns
cols0 = t0.column_names
mismatch = []
for f in files[1:]:
    if pq.read_schema(f).names != cols0:
        mismatch.append(f)
print("Schema mismatches:", len(mismatch))
if mismatch:
    print("First mismatch:", mismatch[0])

# Quick label presence scan across tiles
import numpy as np
tiles_with_labels = 0
total_labeled = 0
for f in files:
    col = pq.read_table(f, columns=["label"])["label"].to_numpy()
    nz = int(np.count_nonzero(col))
    tiles_with_labels += (nz > 0)
    total_labeled += nz

print(f"Tiles with any labels: {tiles_with_labels} / {len(files)}")
print(f"Total labeled pixels (nonzero label): {total_labeled:,}")

from pathlib import Path
import pyarrow.dataset as ds
import numpy as np

PARQUET_DIR = Path("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_new")
dataset = ds.dataset(str(PARQUET_DIR), format="parquet")

# label histogram
tbl = dataset.to_table(columns=["label"])
labels = tbl.column("label").to_numpy()
unique, counts = np.unique(labels, return_counts=True)
label_hist = dict(zip(unique.tolist(), counts.tolist()))
print("Label histogram:", label_hist)
print("Total labeled pixels:", int((labels != 0).sum()))

import pyarrow.parquet as pq
print(pq.read_schema("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/Parquet_Save/Copy of tile_0023.parquet"))



table = pq.read_table("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/Parquet_Save/Copy of tile_0023.parquet")
print(table.num_rows)   # cell count
print(table.num_columns)

import os, re

def tile_index_from_path(p: str) -> int:
    name = os.path.basename(p).strip().lower()
    # try common patterns, in order
    pats = [
        r'^tile_(\d+)\.parquet$',                 # tile_0000.parquet
        r'^tile_(\d+)\..*parquet$',               # tile_0000.snappy.parquet
        r'^(?:emb_|lab_)?tile_(\d+)(?:_.*)?\.parquet$',  # emb_tile_0_...parquet
    ]
    for pat in pats:
        m = re.match(pat, name)
        if m:
            return int(m.group(1))
    raise ValueError(f"Could not parse tile index from filename: {name!r}")

!pip -q install pyarrow folium

import os, glob, re
import pyarrow.parquet as pq
import folium

# ====== CONFIG ======
OLD_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_final"
NEW_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2025_emb_only"

# ====== HELPERS ======
def lonlat_bounds_from_parquet(path):
    """
    Use Parquet column stats (no full load) to get [minLon, minLat, maxLon, maxLat].
    Falls back to reading lon/lat if stats not present.
    """
    pf = pq.ParquetFile(path)
    min_lon = min_lat = float('inf')
    max_lon = max_lat = float('-inf')
    have_stats = False

    for rg in range(pf.num_row_groups):
        md = pf.metadata.row_group(rg)
        col_ix = {md.column(i).path_in_schema: i for i in range(md.num_columns)}
        for col_name, is_lon in (('lon', True), ('lat', False)):
            if col_name in col_ix:
                cmeta = md.column(col_ix[col_name])
                stats = cmeta.statistics
                if stats and stats.has_min_max:
                    have_stats = True
                    if is_lon:
                        min_lon = min(min_lon, float(stats.min))
                        max_lon = max(max_lon, float(stats.max))
                    else:
                        min_lat = min(min_lat, float(stats.min))
                        max_lat = max(max_lat, float(stats.max))

    if not have_stats:
        table = pq.read_table(path, columns=['lon', 'lat'])
        min_lon = float(table['lon'].min())
        max_lon = float(table['lon'].max())
        min_lat = float(table['lat'].min())
        max_lat = float(table['lat'].max())

    return min_lon, min_lat, max_lon, max_lat

def tile_index_from_path(path):
    m = re.search(r"tile_(\d+)\.parquet", os.path.basename(path))
    if not m:
        raise ValueError(f"Cannot parse index from {path}")
    return int(m.group(1))

# ====== COLLECT FILES ======
old_parqs = sorted(glob.glob(os.path.join(OLD_DIR, "tile_*.parquet")))
new_parqs = sorted(glob.glob(os.path.join(NEW_DIR, "tile_*.parquet")))

print(f"Found {len(old_parqs)} old (2017) labeled tiles")
print(f"Found {len(new_parqs)} new (2025) emb-only tiles")

# ====== BUILD MAP ======
# Rough center on Sonoma
m = folium.Map(location=[38.5, -122.9], zoom_start=9, control_scale=True)

# Layer groups so you can toggle
old_layer = folium.FeatureGroup(name="2017 labeled tiles", show=True)
new_layer = folium.FeatureGroup(name="2025 embedding tiles", show=True)

# 2017 labeled tiles (use e.g. yellow)
for p in old_parqs:
    try:
        idx = tile_index_from_path(p)
    except ValueError:
        continue
    xmin, ymin, xmax, ymax = lonlat_bounds_from_parquet(p)
    folium.Rectangle(
        bounds=[(ymin, xmin), (ymax, xmax)],
        tooltip=f"2017 tile_{idx:04d}",
        fill=True,
        weight=2,
        color="orange",
    ).add_to(old_layer)

# 2025 embedding-only tiles (use e.g. blue)
for p in new_parqs:
    try:
        idx = tile_index_from_path(p)
    except ValueError:
        continue
    xmin, ymin, xmax, ymax = lonlat_bounds_from_parquet(p)
    folium.Rectangle(
        bounds=[(ymin, xmin), (ymax, xmax)],
        tooltip=f"2025 tile_{idx:04d}",
        fill=False,
        weight=1,
        color="blue",
    ).add_to(new_layer)

old_layer.add_to(m)
new_layer.add_to(m)
folium.LayerControl().add_to(m)

m

import pyarrow.parquet as pq
import numpy as np
import random, glob, os

PARQ_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2025_emb_only"
files = sorted(glob.glob(os.path.join(PARQ_DIR, "tile_*.parquet")))

# Pick a random tile
f = random.choice(files)
print("Testing:", f)

table = pq.read_table(f, columns=[f"A{k:02d}" for k in range(64)])
arr = table.to_pandas()

print("Rows:", len(arr))
print("Percent NaN:", arr.isna().mean().mean())
print(arr.head())

# --- tile decoder / summarizer ---

import os
import math
import pandas as pd

# use pyarrow for speed; falls back to pandas for safety
try:
    import pyarrow.parquet as pq
    _USE_PYARROW = True
except Exception:
    _USE_PYARROW = False

PIXEL_TO_KM2 = 1e-4

LABEL_MAP = {
    0:  "Unclassified / background",
    1:  "Annual Cropland",
    2:  "Barren & Sparsely Vegetated",
    3:  "Developed",
    4:  "Forest Sliver",
    5:  "Herbaceous",
    6:  "Intensively Managed Hayfield",
    7:  "Irrigated Pasture",
    8:  "Major Roads",
    9:  "Native Forest",
    10: "Non-native Forest & Woodland",
    11: "Non-native Shrub",
    12: "Nursery / Ornamental",
    13: "Orchard / Grove",
    14: "Perennial Agriculture",
    15: "Shrub",
    16: "Urban Window",
    17: "Vineyard",
    18: "Vineyard Replant",
    19: "Water",
}

def _read_label_series(parquet_path: str) -> pd.Series:
    """Return a pandas Series of label codes from the parquet."""
    if _USE_PYARROW:
        tbl = pq.read_table(parquet_path, columns=["label"])
        s = tbl.column("label").to_pandas()
    else:
        s = pd.read_parquet(parquet_path, columns=["label"])
        if isinstance(s, pd.DataFrame):
            s = s["label"]
    return s.astype("int32", copy=False)

def summarize_tile(parquet_path: str, drop_unclassified: bool = False) -> pd.DataFrame:
    """
    Summarize label distribution for a single tile parquet.
    Returns a DataFrame with: code, label, pixels, area_km2, pct.
    """
    labels = _read_label_series(parquet_path)
    total = int(labels.size)

    vc = labels.value_counts().sort_values(ascending=False)
    df = (
        vc.rename("pixels")
          .rename_axis("code")
          .reset_index()
          .assign(
              label=lambda d: d["code"].map(LABEL_MAP).fillna("UNKNOWN"),
              area_km2=lambda d: d["pixels"] * PIXEL_TO_KM2,
              pct=lambda d: (d["pixels"] / total) * 100.0,
          )
          .loc[:, ["code", "label", "pixels", "area_km2", "pct"]]
    )

    if drop_unclassified:
        df = df.loc[df["code"] != 0].reset_index(drop=True)

    # Nice formatting for display
    df["area_km2"] = df["area_km2"].round(4)
    df["pct"] = df["pct"].round(4)

    # Add a footer row with totals (area should equal total*1e-4)
    total_row = pd.DataFrame(
        [{
            "code": -1,
            "label": "TOTAL",
            "pixels": total,
            "area_km2": round(total * PIXEL_TO_KM2, 4),
            "pct": 100.0
        }]
    )
    return pd.concat([df, total_row], ignore_index=True)

def check_ocean_tile(parquet_path: str, water_code: int = 19) -> dict:
    """
    For a tile expected to be ocean: verify that any labeled pixels are WATER.
    Returns a dict with counts and pass/fail flag.
    """
    labels = _read_label_series(parquet_path)
    total = int(labels.size)
    nonzero = labels[labels != 0]
    non_water = nonzero[nonzero != water_code]

    return {
        "tile": os.path.basename(parquet_path),
        "total_pixels": total,
        "labeled_pixels": int(nonzero.size),
        "defined_pixels": int(non_water.size),
        "ok": int(non_water.size) == 0,
    }

# ---------- Example usage ----------
p = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_new/tile_0023.parquet"
summary = summarize_tile(p, drop_unclassified=True)
display(summary)               # in Colab/Jupyter
print(check_ocean_tile(p))     # sanity check for ocean tiles

# Optional: save per-tile CSV next to parquet
# summary.to_csv(p.replace(".parquet", "_summary.csv"), index=False)

import os
import pandas as pd
from tqdm import tqdm

# Path to your folder of parquet tiles
PARQUET_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_final"

# Collect parquet file paths
parquet_files = [os.path.join(PARQUET_DIR, f) for f in os.listdir(PARQUET_DIR) if f.endswith(".parquet")]
print(f"Found {len(parquet_files)} parquet files\n")

labeled_tiles = []
unlabeled_tiles = []

# Loop through each parquet and check label presence
for p in tqdm(parquet_files, desc="Checking tiles"):
    try:
        df = pd.read_parquet(p, columns=["label"])  # only load label column for speed
        labels = df["label"].unique()
        if any((labels != 0) & (labels != -1)):
            labeled_tiles.append(p)
        else:
            unlabeled_tiles.append(p)
    except Exception as e:
        print(f"Error reading {p}: {e}")

print(f"\nTiles with at least one valid label: {len(labeled_tiles)}")
print(f"Tiles that are entirely unclassified/unlabeled: {len(unlabeled_tiles)}")

# Optionally print labeled tiles (the ones you want to keep)
for t in unlabeled_tiles:
    print(t)

import os
import pandas as pd
from tqdm import tqdm

# === CONFIG ===
PARQUET_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_final"
DELETE_FILES = True  # Set to False to preview first

# Get all parquet paths
parquet_files = [os.path.join(PARQUET_DIR, f) for f in os.listdir(PARQUET_DIR) if f.endswith(".parquet")]
print(f"Found {len(parquet_files)} parquet tiles\n")

unlabeled_tiles = []

# Identify unlabeled tiles
for p in tqdm(parquet_files, desc="Scanning tiles"):
    try:
        df = pd.read_parquet(p, columns=["label"])
        labels = df["label"].unique()
        if all((labels == 0) | (labels == -1)):
            unlabeled_tiles.append(p)
    except Exception as e:
        print(f"Error reading {p}: {e}")

print(f"\nUnlabeled tiles found: {len(unlabeled_tiles)}")

# Print before deletion
for f in unlabeled_tiles:
    print(f)

# Optional deletion
if DELETE_FILES and unlabeled_tiles:
    confirm = input("\nType 'yes' to confirm deletion of these unlabeled tiles: ").strip().lower()
    if confirm == "yes":
        for f in unlabeled_tiles:
            try:
                os.remove(f)
            except Exception as e:
                print(f"Failed to delete {f}: {e}")
        print(f"\n✅ Deleted {len(unlabeled_tiles)} unlabeled tiles.")
    else:
        print("\nDeletion canceled.")
else:
    print("\nDELETE_FILES is False — no files deleted.")

import os, pandas as pd, numpy as np
from collections import Counter, defaultdict

PARQUET_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_final"

label_names = {
  0: "Unclassified",
  1:"Annual Cropland", 2:"Barren & Sparsely Vegetated", 3:"Developed", 4:"Forest Sliver",
  5:"Herbaceous", 6:"Intensively Managed Hayfield", 7:"Irrigated Pasture", 8:"Major Roads",
  9:"Native Forest", 10:"Non-native Forest & Woodland", 11:"Non-native Shrub",
  12:"Nursery / Ornamental", 13:"Orchard / Grove", 14:"Perennial Agriculture",
  15:"Shrub", 16:"Urban Window", 17:"Vineyard", 18:"Vineyard Replant", 19:"Water"
}

parquets = sorted([os.path.join(PARQUET_DIR,f) for f in os.listdir(PARQUET_DIR) if f.endswith(".parquet")])

tile_hist = {}
tile_classes = {}
for p in parquets:
    df = pd.read_parquet(p, columns=["label"])
    counts = df["label"].value_counts().to_dict()
    tile_hist[p] = counts
    # drop unclassified codes
    present = sorted([k for k,v in counts.items() if k not in (0,-1)])
    tile_classes[p] = present

# Overall class totals
overall = Counter()
for h in tile_hist.values():
    for k,v in h.items():
        if k not in (0,-1):
            overall[k] += v

print("Tiles with any labels:", sum(len(cs)>0 for cs in tile_classes.values()))
print("Overall labeled pixel counts per class:")
for k,v in sorted(overall.items()):
    print(f"{k:2d} {label_names[k]:35s} {v:,}")

# Mark labeled tiles only
labeled_tiles = [t for t,cls in tile_classes.items() if len(cls)>0]

needed = set(k for k in overall if k not in (0,-1))
train, remaining = [], set(labeled_tiles)

while needed:
    best = max(remaining, key=lambda t: len(set(tile_classes[t]) & needed))
    train.append(best); remaining.remove(best)
    needed -= set(tile_classes[best])

for t in list(remaining):
    if len(train) >= 20: break
    train.append(t); remaining.remove(t)


rem_list = list(remaining)
val = rem_list[::2]
test = rem_list[1::2]

def coverage(tiles):
    s = set()
    for t in tiles: s |= set(tile_classes[t])
    return sorted(s)

print(f"TRAIN {len(train)} tiles, covers classes: {coverage(train)}")
print(f"VAL   {len(val)} tiles, covers classes: {coverage(val)}")
print(f"TEST  {len(test)} tiles, covers classes: {coverage(test)}")

# 1) Install deps once per session
!pip -q install pyarrow folium pillow numpy

# 2) Run helper
import os, tempfile
import numpy as np
import pyarrow.parquet as pq
import folium
from PIL import Image

def show_labeled_pixels(tile_parquet_path, bins=512, label_ok=(0, -1)):
    """
    Paint labeled pixels for a single Parquet tile (cells with label not in label_ok).
    - bins: raster resolution used for the overlay (higher = finer, but heavier)
    - label_ok: codes considered 'unlabeled' (0 and -1 by default)
    """
    # Read minimal columns
    tbl = pq.read_table(tile_parquet_path, columns=["lon", "lat", "label"])
    df = tbl.to_pandas()

    # Keep only labeled cells
    unlabeled = set(label_ok)
    msk = ~df["label"].isin(unlabeled)
    if msk.sum() == 0:
        print("No labeled pixels in this tile.")
        # Still show tile extent for context
        xmin, xmax = df["lon"].min(), df["lon"].max()
        ymin, ymax = df["lat"].min(), df["lat"].max()
        m = folium.Map(location=[(ymin+ymax)/2, (xmin+xmax)/2], zoom_start=12, control_scale=True)
        folium.Rectangle(bounds=[(ymin, xmin), (ymax, xmax)], color="gray", weight=2, fill=False).add_to(m)
        display(m)
        return

    lon = df.loc[msk, "lon"].to_numpy()
    lat = df.loc[msk, "lat"].to_numpy()

    # Tile bounds
    xmin, xmax = df["lon"].min(), df["lon"].max()
    ymin, ymax = df["lat"].min(), df["lat"].max()

    # Create a binary mask in a small raster grid (bins x bins)
    # bin edges
    x_edges = np.linspace(xmin, xmax, bins + 1)
    y_edges = np.linspace(ymin, ymax, bins + 1)

    # Assign each labeled point to a bin
    xi = np.clip(np.searchsorted(x_edges, lon, side="right") - 1, 0, bins - 1)
    yi = np.clip(np.searchsorted(y_edges, lat, side="right") - 1, 0, bins - 1)

    mask = np.zeros((bins, bins), dtype=np.uint8)
    mask[yi, xi] = 1  # any labeled cell marks the bin

    # Make an RGBA image: red where mask=1, fully transparent elsewhere
    rgba = np.zeros((bins, bins, 4), dtype=np.uint8)
    rgba[..., 0] = (mask * 255)            # R
    rgba[..., 3] = (mask * 200)            # Alpha (200/255)
    # Flip vertically so image aligns with map (top-left origin vs lat ascending)
    rgba = np.flipud(rgba)

    # Save to temp PNG
    tmp_png = os.path.join(tempfile.gettempdir(), "tile_labeled_overlay.png")
    Image.fromarray(rgba, mode="RGBA").save(tmp_png)

    # Folium map centered on tile
    m = folium.Map(location=[(ymin+ymax)/2, (xmin+xmax)/2], zoom_start=12, control_scale=True)

    # Outline the tile
    folium.Rectangle(bounds=[(ymin, xmin), (ymax, xmax)], color="black", weight=1, fill=False).add_to(m)

    # Add raster overlay
    folium.raster_layers.ImageOverlay(
        name="Labeled pixels",
        image=tmp_png,
        bounds=[(ymin, xmin), (ymax, xmax)],
        opacity=1.0,
        interactive=False,
        cross_origin=False
    ).add_to(m)

    folium.LayerControl().add_to(m)
    display(m)

# 3) Call it on one tile
show_labeled_pixels("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_filtered/tile_0033.parquet")

!pip -q install geopandas pyarrow shapely tqdm

import os
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point
from tqdm import tqdm

# === CONFIG ===
PARQ_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_new"
FIRE_SHP = "/content/drive/Shared drives/Sonoma Landcover Classification Project/firedata/UpdateFireMap2017/sonoma_fire_perimeters_2017_2020.shp"

# Use a *different* output dir so you don't clobber originals
OUT_DIR  = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_new_noburn"
os.makedirs(OUT_DIR, exist_ok=True)

# === 1. Load fire boundaries ===
fires = gpd.read_file(FIRE_SHP)

# Make sure CRS is defined and in WGS84
fires = fires.set_crs("EPSG:4326", inplace=False)
fires = fires.to_crs("EPSG:4326")

# === 2. Process each parquet ===
tiles = [
    os.path.join(PARQ_DIR, f)
    for f in os.listdir(PARQ_DIR)
    if f.endswith(".parquet")
]

for tile in tqdm(tiles, desc="Filtering burned cells"):
    # Read full tile (all columns, including embeddings)
    df_full = pd.read_parquet(tile)

    # Build GeoDataFrame using lon/lat, but keep the same index
    gdf = gpd.GeoDataFrame(
        df_full[["lon", "lat"]],
        geometry=gpd.points_from_xy(df_full.lon, df_full.lat),
        crs="EPSG:4326",
    )

    # Spatial join to find burned cells
    burned = gpd.sjoin(gdf, fires, how="inner", predicate="within")

    if not burned.empty:
        burned_idx = burned.index
        df_filtered = df_full.drop(index=burned_idx)
    else:
        df_filtered = df_full

    # Save filtered parquet (all columns preserved)
    out_path = os.path.join(OUT_DIR, os.path.basename(tile))
    df_filtered.to_parquet(out_path, index=False)

print(f"\nDone. Filtered tiles saved to {OUT_DIR}")

# 1) deps
!pip -q install pyarrow folium pillow numpy

# 2) code
import os, glob, tempfile
import numpy as np
import pyarrow.parquet as pq
from PIL import Image
import folium

# === CONFIG ===
PARQ_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_final"
BINS_PER_TILE = 512          # raster resolution per tile (↑ finer, ↑ cost)
LABEL_OK = {0, -1}           # treat these as "unlabeled" (ignored)
MODE = "mosaic"              # "mosaic" (single overlay) or "multi" (one overlay per tile)
CENTER = (38.5, -122.9)      # map center; adjust if needed
ZOOM = 9

# ---------- helpers ----------
def read_minimal(path, cols):
    """Small helper: read specific columns to pandas (pyarrow backend)."""
    tbl = pq.read_table(path, columns=cols)
    return tbl.to_pandas()

def get_bounds(path):
    """Tile bounds [xmin, ymin, xmax, ymax] from lon/lat columns."""
    df = read_minimal(path, ["lon", "lat"])
    return float(df.lon.min()), float(df.lat.min()), float(df.lon.max()), float(df.lat.max())

def rasterize_tile_mask(path, bins, label_ok):
    """
    Return (mask[bins,bins], bounds) where mask=1 where labeled pixels occur.
    Uses lon/lat + label columns only.
    """
    df = read_minimal(path, ["lon", "lat", "label"])
    xmin, ymin, xmax, ymax = df.lon.min(), df.lat.min(), df.lon.max(), df.lat.max()
    msk_pts = ~df["label"].isin(label_ok)
    if not msk_pts.any():
        return np.zeros((bins, bins), dtype=np.uint8), (xmin, ymin, xmax, ymax)

    lon = df.loc[msk_pts, "lon"].to_numpy()
    lat = df.loc[msk_pts, "lat"].to_numpy()

    # bin edges
    x_edges = np.linspace(xmin, xmax, bins + 1)
    y_edges = np.linspace(ymin, ymax, bins + 1)

    xi = np.clip(np.searchsorted(x_edges, lon, side="right") - 1, 0, bins - 1)
    yi = np.clip(np.searchsorted(y_edges, lat, side="right") - 1, 0, bins - 1)

    mask = np.zeros((bins, bins), dtype=np.uint8)
    mask[yi, xi] = 1
    return mask, (xmin, ymin, xmax, ymax)

def save_rgba(mask, path_png):
    """
    Save binary mask (0/1) as red RGBA PNG (north-up).
    Input mask index [row=y, col=x] assumed south->north increasing; flip for display.
    """
    m = np.flipud(mask)  # folium expects top-left origin
    rgba = np.zeros((m.shape[0], m.shape[1], 4), dtype=np.uint8)
    rgba[..., 0] = m * 255       # red
    rgba[..., 3] = m * 200       # alpha
    Image.fromarray(rgba, mode="RGBA").save(path_png)

# ---------- main ----------
parquets = sorted(glob.glob(os.path.join(PARQ_DIR, "tile_*.parquet")))
if not parquets:
    raise FileNotFoundError(f"No parquet files found under {PARQ_DIR}")

# Build map
m = folium.Map(location=CENTER, zoom_start=ZOOM, control_scale=True)

if MODE == "multi":
    # One overlay per tile
    for p in parquets:
        mask, (xmin, ymin, xmax, ymax) = rasterize_tile_mask(p, BINS_PER_TILE, LABEL_OK)
        # Skip empty
        if mask.sum() == 0:
            # Optionally draw outline for context
            folium.Rectangle(bounds=[(ymin, xmin), (ymax, xmax)],
                             color="gray", weight=1, fill=False,
                             tooltip=f"{os.path.basename(p)} | 0% labeled").add_to(m)
            continue

        png = os.path.join(tempfile.gettempdir(), f"{os.path.basename(p)}.png")
        save_rgba(mask, png)

        folium.raster_layers.ImageOverlay(
            name=f"{os.path.basename(p)}",
            image=png,
            bounds=[(ymin, xmin), (ymax, xmax)],
            opacity=1.0,
            interactive=False,
            cross_origin=False
        ).add_to(m)

        # outline
        folium.Rectangle(bounds=[(ymin, xmin), (ymax, xmax)],
                         color="black", weight=1, fill=False).add_to(m)

    folium.LayerControl().add_to(m)
    display(m)

else:
    # MOSAIC mode: single large canvas
    # 1) Determine global bounds & per-degree resolution from the first non-empty tile
    #    (Assumes a consistent grid; OK for your 0.16° tiles)
    first_bounds = None
    first_nonempty_bins = None

    global_xmin = +1e9
    global_ymin = +1e9
    global_xmax = -1e9
    global_ymax = -1e9

    # First pass: compute global bounds and capture the per-degree pixel scale
    for p in parquets:
        mask, (xmin, ymin, xmax, ymax) = rasterize_tile_mask(p, BINS_PER_TILE, LABEL_OK)
        global_xmin = min(global_xmin, xmin)
        global_ymin = min(global_ymin, ymin)
        global_xmax = max(global_xmax, xmax)
        global_ymax = max(global_ymax, ymax)

        if mask.sum() > 0 and first_bounds is None:
            first_bounds = (xmin, ymin, xmax, ymax)
            first_nonempty_bins = BINS_PER_TILE

    if first_bounds is None:
        # Nothing labeled anywhere; still draw tile outlines for context
        for p in parquets:
            xmin, ymin, xmax, ymax = get_bounds(p)
            folium.Rectangle(bounds=[(ymin, xmin), (ymax, xmax)],
                             color="gray", weight=1, fill=False).add_to(m)
        display(m)
    else:
        # 2) Derive mosaic resolution from one tile's res to keep scale consistent
        txmin, tymin, txmax, tymax = first_bounds
        res_x = first_nonempty_bins / (txmax - txmin)   # pixels per degree in lon
        res_y = first_nonempty_bins / (tymax - tymin)   # pixels per degree in lat

        W = int(np.ceil((global_xmax - global_xmin) * res_x))
        H = int(np.ceil((global_ymax - global_ymin) * res_y))
        W = max(W, 1); H = max(H, 1)

        mosaic = np.zeros((H, W), dtype=np.uint8)

        # 3) Paint each tile's labeled mask into mosaic coords
        for p in parquets:
            mask, (xmin, ymin, xmax, ymax) = rasterize_tile_mask(p, BINS_PER_TILE, LABEL_OK)
            if mask.sum() == 0:
                continue

            # destination indices in mosaic
            x0 = int(np.floor((xmin - global_xmin) * res_x))
            y0 = int(np.floor((ymin - global_ymin) * res_y))
            x1 = int(np.ceil((xmax - global_xmin) * res_x))
            y1 = int(np.ceil((ymax - global_ymin) * res_y))

            # ensure shape match when rounding changes edges
            dst_w = max(x1 - x0, 1)
            dst_h = max(y1 - y0, 1)

            # resize mask to destination box if needed (nearest)
            if (dst_h, dst_w) != mask.shape:
                mask_img = Image.fromarray(mask, mode="L").resize((dst_w, dst_h), resample=Image.NEAREST)
                mask_resized = np.array(mask_img, dtype=np.uint8)
                mask_resized[mask_resized > 0] = 1
            else:
                mask_resized = mask

            # composite (union)
            mosaic[y0:y1, x0:x1] = np.maximum(mosaic[y0:y1, x0:x1], mask_resized)

        # 4) Save RGBA PNG and overlay once
        png = os.path.join(tempfile.gettempdir(), "mosaic_labeled.png")
        save_rgba(mosaic, png)

        folium.raster_layers.ImageOverlay(
            name="Labeled pixels (mosaic)",
            image=png,
            bounds=[(global_ymin, global_xmin), (global_ymax, global_xmax)],
            opacity=1.0,
            interactive=False,
            cross_origin=False
        ).add_to(m)

        # Optional: also draw tile frames (light)
        for p in parquets:
            xmin, ymin, xmax, ymax = get_bounds(p)
            folium.Rectangle(bounds=[(ymin, xmin), (ymax, xmax)],
                             color="#666", weight=1, fill=False).add_to(m)

        folium.LayerControl().add_to(m)
        display(m)

!pip -q install pyarrow folium pillow numpy

import os, glob, tempfile
import numpy as np
import pyarrow.parquet as pq
from PIL import Image
import folium

# === CONFIG ===
PARQ_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_final"
BINS_PER_TILE = 512
LABEL_IGNORE = {0, -1}     # unlabeled / background
CENTER = (38.5, -122.9)
ZOOM = 9

# label → RGB colormap
COLORMAP = {
    1:(255,255,191),  2:(255,224,102),  3:(255,0,0),      4:(255,153,51),
    5:(181,255,181),  6:(204,255,153),  7:(153,255,102),  8:(255,204,0),
    9:(0,153,0),     10:(51,204,51),   11:(153,255,204), 12:(255,204,229),
    13:(204,153,0),  14:(204,255,255), 15:(0,255,128),   16:(255,102,102),
    17:(128,64,0),   18:(153,102,255), 19:(0,0,255)
}

# ---------- helpers ----------
def read_minimal(path, cols):
    tbl = pq.read_table(path, columns=cols)
    return tbl.to_pandas()

def rasterize_labels(path, bins):
    df = read_minimal(path, ["lon", "lat", "label"])
    xmin, ymin, xmax, ymax = df.lon.min(), df.lat.min(), df.lon.max(), df.lat.max()
    valid = ~df["label"].isin(LABEL_IGNORE)
    if not valid.any():
        return None, (xmin, ymin, xmax, ymax)
    lon, lat, lab = df.loc[valid, ["lon","lat","label"]].to_numpy().T
    x_edges = np.linspace(xmin, xmax, bins+1)
    y_edges = np.linspace(ymin, ymax, bins+1)
    xi = np.clip(np.searchsorted(x_edges, lon, "right")-1, 0, bins-1)
    yi = np.clip(np.searchsorted(y_edges, lat, "right")-1, 0, bins-1)
    canvas = np.zeros((bins, bins), dtype=np.uint8)
    canvas[yi, xi] = lab
    return canvas, (xmin, ymin, xmax, ymax)

def save_color_mask(label_img, path_png):
    m = np.flipud(label_img)    # north-up for display
    h, w = m.shape
    rgba = np.zeros((h,w,4), dtype=np.uint8)
    for lbl, rgb in COLORMAP.items():
        mask = m==lbl
        if not mask.any(): continue
        rgba[mask,0] = rgb[0]; rgba[mask,1] = rgb[1]; rgba[mask,2] = rgb[2]
        rgba[mask,3] = 180
    Image.fromarray(rgba, mode="RGBA").save(path_png)

# ---------- main ----------
parquets = sorted(glob.glob(os.path.join(PARQ_DIR,"tile_*.parquet")))
m = folium.Map(location=CENTER, zoom_start=ZOOM, control_scale=True)

for p in parquets:
    label_img, (xmin, ymin, xmax, ymax) = rasterize_labels(p, BINS_PER_TILE)
    if label_img is None:
        continue
    tmp_png = os.path.join(tempfile.gettempdir(), os.path.basename(p)+".png")
    save_color_mask(label_img, tmp_png)
    folium.raster_layers.ImageOverlay(
        name=os.path.basename(p),
        image=tmp_png,
        bounds=[(ymin,xmin),(ymax,xmax)],
        opacity=0.7,
        interactive=False,
        cross_origin=False
    ).add_to(m)

folium.LayerControl().add_to(m)
m

import pandas as pd
from collections import Counter

# Example: quickly check label co-occurrence within "road" bounding boxes
df = pd.read_parquet("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_filtered/tile_0072.parquet")
road_mask = (df['label'] == 8)
around_road = df.loc[road_mask, 'label'].value_counts()
print(around_road)

import os, glob
import pandas as pd

PARQ_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_final"

parquets = sorted(glob.glob(os.path.join(PARQ_DIR, "tile_*.parquet")))
print(f"Found {len(parquets)} parquet tiles")

for path in parquets:
    print("Cleaning:", os.path.basename(path))
    df = pd.read_parquet(path)

    # Vineyard Replant (18) → Vineyard (17)
    df.loc[df["label"] == 18, "label"] = 17

    # Roads (8) → Developed (3)
    df.loc[df["label"] == 8, "label"] = 3

    # Do NOT drop label==0 rows; just keep them as background
    df.to_parquet(path, index=False)

print("Done — labels updated, unlabeled pixels kept.")

import os
import pandas as pd
from tqdm import tqdm

PARQ_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_final"

print("Merging Urban Window → Developed...")

for fname in tqdm(os.listdir(PARQ_DIR)):
    if not fname.endswith(".parquet"):
        continue

    path = os.path.join(PARQ_DIR, fname)

    # Load parquet tile
    df = pd.read_parquet(path)

    # If tile contains any Urban Window pixels
    if (df['label'] == 16).any():
        # Merge into Developed (3)
        df.loc[df['label'] == 16, "label"] = 3

        # Overwrite original
        df.to_parquet(path, index=False)

print("Done — all Urban Window pixels have been merged into Developed.")

import os, glob, random
import pandas as pd

# ==== CONFIG ====
PARQ_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_final"
IGNORE_LABELS = {0, -1}   # treat these as unlabeled/background

# Embedding band names (A00..A63)
EMB_COLS = [f"A{i:02d}" for i in range(64)]

# Collect all parquet tiles
parquet_files = sorted(glob.glob(os.path.join(PARQ_DIR, "tile_*.parquet")))
print(f"Found {len(parquet_files)} tiles")

def sample_random_labeled_cell():
    """Pick a random tile and a random labeled cell within it, then print info."""
    # Shuffle copy of file list so we don't always hit the same tile first
    candidates = parquet_files.copy()
    random.shuffle(candidates)

    for path in candidates:
        df = pd.read_parquet(path)  # full row needed for embeddings

        # Keep only labeled cells
        mask = ~df["label"].isin(IGNORE_LABELS)
        if not mask.any():
            continue  # no labeled cells in this tile, try next

        # Sample one random labeled row
        row = df[mask].sample(1).iloc[0]

        print("=== Random labeled cell ===")
        print("Tile file :", os.path.basename(path))
        print("cell_id   :", row.get("cell_id", None))
        print("lon, lat  :", float(row["lon"]), float(row["lat"]))
        print("label     :", int(row["label"]))
        print()

        # Show first few embedding values for a quick sanity check
        emb_vec = [row[c] for c in EMB_COLS]
        print("Embedding length:", len(emb_vec))
        print("64 dims   :", emb_vec[:64])
        return row  # return full row in case you want to inspect it further

    raise RuntimeError("No labeled cells found in any tile.")

# Run once to inspect a random labeled cell
sample_row = sample_random_labeled_cell()

!pip -q install rasterio numpy

import os, glob
import numpy as np
import rasterio

# folder with raw embedding GeoTIFFs from GEE
EMB_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/emb_tiles_2017"  # <-- change

emb_files = sorted(glob.glob(os.path.join(EMB_DIR, "Copy of emb_tile_*.tif")))
print(f"Found {len(emb_files)} emb tiles")

def check_emb_tile(path, sample_bands=(1, 32, 64)):
    with rasterio.open(path) as src:
        h, w = src.height, src.width
        print(f"\n{os.path.basename(path)}: bands={src.count}, size={w}x{h}, dtype={src.dtypes[0]}")
        print("  nodata value:", src.nodata)

        for b in sample_bands:
            if b > src.count:
                continue
            arr = src.read(b, masked=True)      # mask nodata as masked elements
            total = arr.size
            valid = (~arr.mask).sum()
            valid_frac = valid / total
            if valid > 0:
                vmin = float(arr.data[~arr.mask].min())
                vmax = float(arr.data[~arr.mask].max())
            else:
                vmin = vmax = np.nan
            print(f"  band {b:2d}: valid {valid}/{total} ({valid_frac:.3%}), "
                  f"min={vmin:.4f}, max={vmax:.4f}")

# Check first few tiles (change slice if you want all)
for f in emb_files[:5]:
    check_emb_tile(f)

import rasterio
import numpy as np

path = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/emb_tiles_2017/Copy of emb_tile_2.tif"  # adjust

with rasterio.open(path) as src:
    print("bands:", src.count, "size:", src.width, "x", src.height)
    arr = src.read(1, masked=True)
    frac_masked = np.mean(arr.mask)
    print("fraction masked:", frac_masked)
    print("value range (non-masked):", float(arr.min()), float(arr.max()))



import os
import glob
import pyarrow.parquet as pq
import numpy as np

# Folder containing your existing parquet tiles
PARQ_DIR = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_new"

def tile_bounds(path):
    """Return (min_lon, max_lon, min_lat, max_lat) for a parquet tile."""
    pf = pq.ParquetFile(path)
    min_lon = min_lat = float('inf')
    max_lon = max_lat = float('-inf')

    # Use row-group stats if available (fast)
    for rg in range(pf.num_row_groups):
        md = pf.metadata.row_group(rg)
        col_ix = {md.column(i).path_in_schema: i for i in range(md.num_columns)}
        for col_name, is_lon in (('lon', True), ('lat', False)):
            if col_name in col_ix:
                cmeta = md.column(col_ix[col_name])
                stats = cmeta.statistics
                if stats and stats.has_min_max:
                    if is_lon:
                        min_lon = min(min_lon, float(stats.min))
                        max_lon = max(max_lon, float(stats.max))
                    else:
                        min_lat = min(min_lat, float(stats.min))
                        max_lat = max(max_lat, float(stats.max))

    # Fallback if no stats
    if not np.isfinite(min_lon):
        tbl = pq.read_table(path, columns=["lon", "lat"])
        lon = tbl["lon"].to_numpy()
        lat = tbl["lat"].to_numpy()
        min_lon, max_lon = lon.min(), lon.max()
        min_lat, max_lat = lat.min(), lat.max()

    return min_lon, max_lon, min_lat, max_lat

# Locate the two tiles
tile_24 = os.path.join(PARQ_DIR, "Copy of tile_0024.parquet")
tile_90 = os.path.join(PARQ_DIR, "Copy of tile_0090.parquet")

for p in (tile_24, tile_90):
    if not os.path.exists(p):
        raise FileNotFoundError(p)

# Get bounds for each
lon_min_24, lon_max_24, lat_min_24, lat_max_24 = tile_bounds(tile_24)
lon_min_90, lon_max_90, lat_min_90, lat_max_90 = tile_bounds(tile_90)

# Combine into overall box from these two tiles
lon_min = min(lon_min_24, lon_min_90)
lon_max = max(lon_max_24, lon_max_90)
lat_min = min(lat_min_24, lat_min_90)
lat_max = max(lat_max_24, lat_max_90)

print("Raw box from 0024 + 0090:")
print(f"  lon: [{lon_min:.6f}, {lon_max:.6f}]")
print(f"  lat: [{lat_min:.6f}, {lat_max:.6f}]")

# Expand by 10%
margin_x = 0.10 * (lon_max - lon_min)
margin_y = 0.10 * (lat_max - lat_min)

XMIN = lon_min - margin_x
XMAX = lon_max + margin_x
YMIN = lat_min - margin_y
YMAX = lat_max + margin_y

print("\nSuggested expanded bounds (10% margin):")
print(f"XMIN = {XMIN:.6f}")
print(f"XMAX = {XMAX:.6f}")
print(f"YMIN = {YMIN:.6f}")
print(f"YMAX = {YMAX:.6f}")

import os
from pathlib import Path

# CHANGE THIS to the directory you want to clean up
DIR = Path("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2017_new")

prefix = "Copy of "

for p in DIR.iterdir():
    if p.is_file() and p.name.startswith(prefix):
        new_name = p.name[len(prefix):]  # strip the prefix
        new_path = p.with_name(new_name)
        print(f"Renaming: {p.name} -> {new_name}")
        p.rename(new_path)

"""# Parquet Generation Embeds Only

"""

#generates unlabeled parquets for our model to apply predictions to, to build final prediction map once training is done.

!pip -q install rasterio pyarrow pyproj tqdm

import re, glob
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq
from pathlib import Path
from tqdm import tqdm
import rasterio
from rasterio.transform import xy as raster_xy
from pyproj import CRS as PJ_CRS, Transformer

# === PATHS: point to your 2025 embedding tiles ===
EMB_DIR = Path("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/sonoma10m_emb_2024")
OUT_DIR = Path("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2025_emb_only")
OUT_DIR.mkdir(parents=True, exist_ok=True)

assert EMB_DIR.is_dir(), f"Missing {EMB_DIR}"
print("Embedding dir:", EMB_DIR)
print("Output dir    :", OUT_DIR)

# extract tile index from filenames like emb_tile_12.tif
idx_pat = re.compile(r'.*_(\d+)\.tif$', re.IGNORECASE)

def idx_of(p: Path):
    m = idx_pat.match(p.name)
    return int(m.group(1)) if m else None

# Collect embedding tiles
emb_files = {idx_of(p): p for p in EMB_DIR.glob("*.tif") if idx_of(p) is not None}
emb_indices = sorted(emb_files.keys())
print(f"Found {len(emb_indices)} embedding tiles")
print("First few indices:", emb_indices[:10])

def to_wgs84_transformer(crs_obj_or_str):
    """Build a pyproj Transformer from raster CRS → EPSG:4326."""
    src = PJ_CRS.from_user_input(crs_obj_or_str)
    dst = PJ_CRS.from_epsg(4326)
    return Transformer.from_crs(src, dst, always_xy=True)

def write_parquet_from_emb(idx: int, emb_path: Path):
    """Create a parquet tile from embeddings only, with dummy label=0."""
    with rasterio.open(emb_path) as E:
        bands = min(64, E.count)  # normally 64
        if bands < 1:
            raise RuntimeError(f"No bands in {emb_path.name}")

        H, W = E.height, E.width
        E64 = E.read(indexes=list(range(1, bands+1))).astype(np.float32)

        A = E64.reshape(bands, -1).T  # (N, bands), row-major

        N = H * W
        y_vec = np.zeros(N, dtype=np.int32)

        rows = np.arange(N, dtype=np.int32) // W
        cols = np.arange(N, dtype=np.int32) %  W

        xs, ys = raster_xy(E.transform, rows, cols, offset='center')
        xs = np.asarray(xs, dtype=np.float64)
        ys = np.asarray(ys, dtype=np.float64)

        tf = to_wgs84_transformer(E.crs if E.crs is not None else "EPSG:32610")
        lons, lats = tf.transform(xs, ys)

        cell_id = (cols.astype(np.int64) << 32) | rows.astype(np.int64)

        names = ["cell_id","i","j","x","y","lon","lat","label"] + [f"A{k:02d}" for k in range(bands)]
        arrays = [
            pa.array(cell_id),
            pa.array(rows), pa.array(cols),
            pa.array(xs), pa.array(ys),
            pa.array(lons), pa.array(lats),
            pa.array(y_vec)  # placeholder labels
        ] + [pa.array(A[:, k]) for k in range(bands)]

        tbl = pa.Table.from_arrays(arrays, names=names)
        out_path = OUT_DIR / f"tile_{idx:04d}.parquet"
        pq.write_table(tbl, out_path, compression="zstd", version="2.6", data_page_version="2.0")
        return out_path

written = []
for idx in tqdm(emb_indices, desc="Emb→Parquet (no labels)"):
    p = write_parquet_from_emb(idx, emb_files[idx])
    written.append(str(p))

print(f"Wrote {len(written)} parquet files to {OUT_DIR}")

import pyarrow.parquet as pq
import glob

files = sorted(glob.glob(str(OUT_DIR / "tile_*.parquet")))
print("Parquets:", len(files))
t0 = pq.read_table(files[0])
print(t0.schema)
print("Rows in first tile:", t0.num_rows)

# check that labels are all zero for now
lbl = pq.read_table(files[0], columns=["label"])["label"].to_numpy()
print("Unique labels in first tile:", np.unique(lbl))