# -*- coding: utf-8 -*-
"""basic_rf_up2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hY1eSLkCS4qLdJuMvkIzNrPjCkstvdrw
"""

import os
from google.colab import drive
drive.mount('/content/drive')

shared_drive_name = "Sonoma Landcover Classification Project"

shared_drive_path = f"/content/drive/Shared drives/{shared_drive_name}"

subdirs = [
    "data/raw",
    "data/processed",
    "data/processed/DataFrames",
    "notebooks",
    "models",
    "exports",
    "figures"
]

for sub in subdirs:
    path = os.path.join(shared_drive_path, sub)
    os.makedirs(path, exist_ok=True)

print(f"Project directories ready under:\n{shared_drive_path}")
!ls -R "$shared_drive_path"

import ee

ee.Authenticate()
ee.Initialize(project='sonoma-lcc')

!pip -q install rasterio pyarrow pyproj tqdm

import os
import geopandas as gpd, rasterio
import pandas as pd
import numpy as np
from shapely.validation import make_valid
import rasterio
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import folium
from tqdm import tqdm
import geopandas as gpd
from shapely.geometry import box
import datetime as dt
from tqdm.auto import tqdm, trange
import time
import re
from pathlib import Path
from rasterio.warp import reproject
from rasterio.enums import Resampling as RS
import pyarrow as pa, pyarrow.parquet as pq
from pyproj import Transformer, CRS

!pip install pyarrow pandas

import pyarrow.parquet as pq
import pyarrow.dataset as ds
import pyarrow as pa
import pandas as pd
import glob, os

import numpy as np
import pandas as pd

df_all = pd.read_parquet("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2024_emb_only")

import joblib
import pandas as pd

rf = joblib.load("/content/drive/Shared drives/Sonoma Landcover Classification Project/models/cnn_model.joblib")
feature_cols = ['A00', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19',
                'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30', 'A31', 'A32', 'A33', 'A34', 'A35', 'A36', 'A37', 'A38', 'A39',
                'A40', 'A41', 'A42', 'A43', 'A44', 'A45', 'A46', 'A47', 'A48', 'A49', 'A50', 'A51', 'A52', 'A53', 'A54', 'A55', 'A56', 'A57', 'A58', 'A59',
                'A60', 'A61', 'A62', 'A63']

import numpy as np

X_new = df_all[feature_cols].to_numpy(dtype=np.float32)

# Predict labels
y_pred = rf.predict(X_new)

# Attach predictions to the DataFrame
df_all['label'] = y_pred



from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

rf = RandomForestClassifier(
    n_estimators=50,
    max_depth= 10,
    random_state=42,
    n_jobs=-1
)

# Train on TRAIN ONLY
rf.fit(X_train, y_train)

# You can use the validation set to compare different hyperparameters if you want
y_val_pred = rf.predict(X_val)
print("Validation accuracy:", accuracy_score(y_val, y_val_pred))

# Final evaluation on TEST
y_test_pred = rf.predict(X_test)

print("Test accuracy:", accuracy_score(y_test, y_test_pred))
print("\nClassification report (test):\n", classification_report(y_test, y_test_pred))

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_test_pred)
disp = ConfusionMatrixDisplay(cm)
disp.plot(xticks_rotation='vertical')
plt.show()

from sklearn.metrics import accuracy_score, classification_report

y_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import ConfusionMatrixDisplay

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(xticks_rotation='vertical', cmap='Blues')

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.title("Confusion Matrix")
plt.show()

cm_norm = confusion_matrix(y_test, y_pred, normalize='true')

plt.figure(figsize=(10,8))
sns.heatmap(cm_norm, annot=False, cmap="Blues")
plt.title("Normalized Confusion Matrix")
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.show()

normalized_cm_all = confusion_matrix(y_test, y_pred, normalize='all')
#normalized_cm_pred = confusion_matrix(y_test, y_pred, normalize='pred')
#normalized_cm_true = confusion_matrix(y_test, y_pred, normalize='true')

pathway = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_labels_1-12/tile_39.parquet"

df = pd.read_parquet(pathway)
X_parquet_test  = df[feature_cols].to_numpy(dtype=np.float32)
y_parquet_test  = df['label'].to_numpy(dtype=np.int32)

y_test_pred = rf.predict(X_parquet_test)

print("Test accuracy:", accuracy_score(y_parquet_test, y_test_pred))
print("\nClassification report (test):\n", classification_report(y_parquet_test, y_test_pred))

import joblib
import os

# Define the path to save the model
model_path = os.path.join(shared_drive_path, "models", "rf2_model.joblib")

# Save the model
joblib.dump(rf, model_path)

print(f"Model saved successfully to: {model_path}")