# -*- coding: utf-8 -*-
"""basic_cnn_up2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKkFT4fmsYKWNUeCFPew7J2LFG7q4C5b
"""

import os
from google.colab import drive
drive.mount('/content/drive')

shared_drive_name = "Sonoma Landcover Classification Project"

shared_drive_path = f"/content/drive/Shared drives/{shared_drive_name}"

subdirs = [
    "data/raw",
    "data/processed",
    "data/processed/DataFrames",
    "notebooks",
    "models",
    "exports",
    "figures"
]

for sub in subdirs:
    path = os.path.join(shared_drive_path, sub)
    os.makedirs(path, exist_ok=True)

print(f"Project directories ready under:\n{shared_drive_path}")
!ls -R "$shared_drive_path"

import ee

ee.Authenticate()
ee.Initialize(project='sonoma-lcc')

!pip -q install rasterio pyarrow pyproj tqdm

import os
import geopandas as gpd, rasterio
import pandas as pd
import numpy as np
from shapely.validation import make_valid
import rasterio
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import folium
from tqdm import tqdm
import geopandas as gpd
from shapely.geometry import box
import datetime as dt
from tqdm.auto import tqdm, trange
import time
import re
from pathlib import Path
from rasterio.warp import reproject
from rasterio.enums import Resampling as RS
import pyarrow as pa, pyarrow.parquet as pq
from pyproj import Transformer, CRS

!pip install pyarrow pandas

import pyarrow.parquet as pq
import pyarrow.dataset as ds
import pyarrow as pa
import pandas as pd
import glob, os



import numpy as np
import pandas as pd
import os, hashlib
import pyarrow.dataset as ds
import pyarrow as pa
import pyarrow.compute as pc

root = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_labels_1-12"
dataset = ds.dataset(root, format="parquet")

feature_cols = [f"A{str(i).zfill(2)}" for i in range(64)]
label_col = "label"
needed_cols = feature_cols + [label_col]

def tile_split(path, train=0.70, val=0.20):
    # deterministic split per file name
    name = os.path.basename(path)
    h = int(hashlib.md5(name.encode()).hexdigest(), 16) % 100000 / 100000.0
    if h < train:
        return "train"
    elif h < train + val:
        return "val"
    else:
        return "test"

train_batches, val_batches, test_batches = [], [], []

for frag in dataset.get_fragments():
    split = tile_split(frag.path)
    for batch in frag.to_batches(columns=needed_cols):
        # keep your usual label filtering (recommended)
        mask = pc.not_equal(batch[label_col], 0)
        batch = batch.filter(mask)

        if split == "train":
            train_batches.append(batch)
        elif split == "val":
            val_batches.append(batch)
        else:
            test_batches.append(batch)

train_table = pa.Table.from_batches(train_batches)
val_table   = pa.Table.from_batches(val_batches)
test_table  = pa.Table.from_batches(test_batches)

df_train = train_table.to_pandas()
df_val   = val_table.to_pandas()
df_test  = test_table.to_pandas()



# --- Train set
X_train = df_train[feature_cols].to_numpy(dtype=np.float32)
y_train = df_train['label'].to_numpy(dtype=np.int32)

# --- Validation set
X_val   = df_val[feature_cols].to_numpy(dtype=np.float32)
y_val   = df_val['label'].to_numpy(dtype=np.int32)

# --- Test set
X_test  = df_test[feature_cols].to_numpy(dtype=np.float32)
y_test  = df_test['label'].to_numpy(dtype=np.int32)

print("Train shape:", X_train.shape, "Val:", X_val.shape, "Test:", X_test.shape)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train_enc = le.fit_transform(y_train)
y_val_enc   = le.transform(y_val)
y_test_enc  = le.transform(y_test)

num_classes = len(le.classes_)
print("Classes:", le.classes_, "num_classes:", num_classes)

del df_train, df_test, df_val
del train_table, test_table, val_table
del train_batches, test_batches, val_batches

n_features = X_train.shape[1]

# X_train_cnn = X_train.reshape(-1, n_features, 1)
# X_test_cnn  = X_test.reshape(-1, n_features, 1)

# num_classes = len(np.unique(y_train))
num_classes = 13
print("n_features:", n_features, "num_classes:", num_classes)
# print("X_train_cnn shape:", X_train_cnn.shape)

import tensorflow as tf
from tensorflow.keras import layers, models

tf.keras.backend.clear_session()

model = models.Sequential([
    layers.Input(shape=(n_features,)),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',  # because y is int labels
    metrics=['accuracy']
)

model.summary()



"""# Task
Balance the `df_train` dataset by performing undersampling on common classes and oversampling on uncommon classes, then recreate `X_train` and `y_train` with the balanced data. First, analyze the current label distribution in `df_train`, define a sampling strategy to achieve a more balanced distribution, and then apply the sampling techniques.

## Analyze Label Distribution

### Subtask:
Calculate the frequency of each label in `df_train` to identify common and uncommon classes.

**Reasoning**:
The subtask requires analyzing the label distribution of the `y_train` array. Converting it to a pandas Series and then using `value_counts()` is an efficient way to calculate the frequency of each label.
"""

y_train_series = pd.Series(y_train)
label_counts = y_train_series.value_counts().sort_index()
print("Label Counts in Training Data:")
print(label_counts)

"""## Define Sampling Strategy

Based on the `label_counts` from the previous step, we can observe that certain classes are significantly more frequent than others (e.g., labels 4 and 7 are very common, while label 1 is rare). To balance the dataset, we will implement a sampling strategy that involves both undersampling the majority classes and oversampling the minority classes.

### Strategy:
1. **Identify the median count:** Calculate the median frequency of all labels. This will serve as a reference point.
2. **Undersample majority classes:** For classes with counts significantly above the median, we will randomly undersample them to bring their counts closer to the median or a defined threshold.
3. **Oversample minority classes:** For classes with counts significantly below the median, we will use techniques like SMOTE or simple replication to increase their counts to a target level, ideally near the median or a slightly higher threshold to ensure sufficient samples for training.

We will aim for a more balanced distribution, ensuring that no single class dominates the training process. The goal is to improve the model's performance on minority classes without sacrificing too much performance on majority classes.

**Reasoning**:
To implement the sampling strategy outlined in the markdown, the first step is to calculate the median count of labels and define a target count for balancing. This will inform the undersampling and oversampling operations.
"""

median_count = label_counts.median()
target_count = int(median_count * 1) # Aim for 1.5 times the median as a target to give minority classes a boost

print(f"Median label count: {median_count}")
print(f"Target count for balanced distribution: {target_count}")

"""**Reasoning**:
Now that the target count for balancing has been established, the next step is to apply undersampling and oversampling techniques to `X_train` and `y_train` based on the defined `target_count`. This involves iterating through each class, undersampling majority classes to `target_count` and oversampling minority classes to `target_count`.


"""

X_train_df = pd.DataFrame(X_train, columns=feature_cols)
X_train_df['label'] = y_train

balanced_data_frames = []

for label in label_counts.index:
    label_df = X_train_df[X_train_df['label'] == label]
    current_count = len(label_df)

    #if current_count > target_count:
        # Undersample majority classes
        # sampled_df = label_df.sample(n=target_count, random_state=42)
    if current_count < target_count:
        # Oversample minority classes using replacement
        sampled_df = label_df.sample(n=target_count, replace=True, random_state=42)
    else:
        # Keep as is if already at target_count
        sampled_df = label_df

    balanced_data_frames.append(sampled_df)

# Concatenate all balanced dataframes
df_train_balanced = pd.concat(balanced_data_frames)

# Shuffle the balanced dataset
df_train_balanced = df_train_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

# Split back into X_train and y_train
X_train_balanced = df_train_balanced[feature_cols].to_numpy(dtype=np.float32)
y_train_balanced = df_train_balanced['label'].to_numpy(dtype=np.int32)

print(f"Original X_train shape: {X_train.shape}")
print(f"Balanced X_train shape: {X_train_balanced.shape}")
print(f"New label counts in balanced training data:\n{pd.Series(y_train_balanced).value_counts().sort_index()}")

del X_train_df, balanced_data_frames, sampled_df, label_df, X_train, y_train

"""## Summary:

### Data Analysis Key Findings

*   **Initial Label Distribution:** The original `df_train` dataset exhibited a severe class imbalance. For instance, label 7 had 12,605,553 samples, while label 1 had significantly fewer, with only 35,848 samples.
*   **Sampling Strategy Defined:** A median label count of 387,584 was identified. To achieve a more balanced distribution, a `target_count` of 581,376 (1.5 times the median) was set for each class.
*   **Balanced Dataset Achieved:**
    *   The original `X_train` had 26,164,039 samples. After balancing, the `X_train_balanced` dataset contained 6,976,512 samples.
    *   The balancing process successfully achieved a perfectly uniform distribution, with each of the 12 classes in `y_train_balanced` now containing exactly 581,376 samples.

### Insights or Next Steps

*   The balanced dataset (`X_train_balanced`, `y_train_balanced`) is now ready for model training, which should mitigate bias towards majority classes and improve the model's performance on previously underrepresented classes.
*   Monitor the model's performance on the balanced data, particularly precision and recall for minority classes, to confirm the effectiveness of the sampling strategy.

"""

history = model.fit(
    X_train_balanced, y_train_balanced,
    validation_data=(X_val, y_val),
    epochs=8,          # start small; tune later
    batch_size=256,
    validation_split=0.0,
    verbose=1
)

test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test loss: {test_loss:.4f}")
print(f"Test accuracy: {test_acc:.4f}")

from sklearn.metrics import confusion_matrix, classification_report

y_pred_probs = model.predict(X_test)
y_pred = y_pred_probs.argmax(axis=1)

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Make predictions on the test set
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)

# Generate the confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=np.arange(num_classes))

# Plot the confusion matrix
fig, ax = plt.subplots(figsize=(10, 10))
sns.heatmap(cm, annot=False, cmap='Blues', fmt='d', ax=ax)
ax.set_xlabel('Predicted Label')
ax.set_ylabel('True Label')
ax.set_title('Confusion Matrix')
plt.show()

cm_norm = confusion_matrix(y_test, y_pred, normalize='true')

plt.figure(figsize=(10,8))
sns.heatmap(cm_norm, annot=False, cmap="Blues")
plt.title("Normalized Confusion Matrix")
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.show()

