# -*- coding: utf-8 -*-
"""basic_cnn_up2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpBfWKN7t1jFG3Zof3jkdkYaYpj8ZU_s
"""

import os
from google.colab import drive
drive.mount('/content/drive')

shared_drive_name = "Sonoma Landcover Classification Project"

shared_drive_path = f"/content/drive/Shared drives/{shared_drive_name}"

subdirs = [
    "data/raw",
    "data/processed",
    "data/processed/DataFrames",
    "notebooks",
    "models",
    "exports",
    "figures"
]

for sub in subdirs:
    path = os.path.join(shared_drive_path, sub)
    os.makedirs(path, exist_ok=True)

print(f"Project directories ready under:\n{shared_drive_path}")
!ls -R "$shared_drive_path"

import ee

ee.Authenticate()
ee.Initialize(project='sonoma-lcc')

!pip -q install rasterio pyarrow pyproj tqdm

import os
import geopandas as gpd, rasterio
import pandas as pd
import numpy as np
from shapely.validation import make_valid
import rasterio
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import folium
from tqdm import tqdm
import geopandas as gpd
from shapely.geometry import box
import datetime as dt
from tqdm.auto import tqdm, trange
import time
import re
from pathlib import Path
from rasterio.warp import reproject
from rasterio.enums import Resampling as RS
import pyarrow as pa, pyarrow.parquet as pq
from pyproj import Transformer, CRS

!pip install pyarrow pandas

import pyarrow.parquet as pq
import pyarrow.dataset as ds
import pyarrow as pa
import pandas as pd
import glob, os

import numpy as np
import pandas as pd

dataset = ds.dataset("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_labels_1-12", format="parquet")

feature_cols = ['A00', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19',
                'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30', 'A31', 'A32', 'A33', 'A34', 'A35', 'A36', 'A37', 'A38', 'A39',
                'A40', 'A41', 'A42', 'A43', 'A44', 'A45', 'A46', 'A47', 'A48', 'A49', 'A50', 'A51', 'A52', 'A53', 'A54', 'A55', 'A56', 'A57', 'A58', 'A59',
                'A60', 'A61', 'A62', 'A63']
label_col = 'label'
needed_cols = feature_cols + [label_col]

import pyarrow.dataset as ds
import pyarrow as pa
import pyarrow.compute as pc

train_batches = []
# val_batches = []
test_batches = []

for batch in dataset.to_batches():
    # Add a random value 0–1 for each row
    rand = pc.random(batch.num_rows)
    batch = batch.append_column("split_rand", rand)

    # Boolean masks
    train_mask = pc.less(batch['split_rand'], 0.85)                # 70%
    # val_mask   = pc.and_(
    #     pc.greater_equal(batch['split_rand'], 0.7),
    #     pc.less(batch['split_rand'], 0.85)                        # 15%
    # )
    test_mask  = pc.greater_equal(batch['split_rand'], 0.85)      # 15%

    train_batches.append(batch.filter(train_mask))
    # val_batches.append(batch.filter(val_mask))
    test_batches.append(batch.filter(test_mask))

# Combine batches
train_table = pa.Table.from_batches(train_batches)
# val_table   = pa.Table.from_batches(val_batches)
test_table  = pa.Table.from_batches(test_batches)

df_train = train_table.to_pandas()
# df_val   = val_table.to_pandas()
df_test  = test_table.to_pandas()

# --- Train set
X_train = df_train[feature_cols].to_numpy(dtype=np.float32)
y_train = df_train['label'].to_numpy(dtype=np.int32)

# --- Validation set
# X_val   = df_val[feature_cols].to_numpy(dtype=np.float32)
# y_val   = df_val['label'].to_numpy(dtype=np.int32)

# --- Test set
X_test  = df_test[feature_cols].to_numpy(dtype=np.float32)
y_test  = df_test['label'].to_numpy(dtype=np.int32)

print("Train shape:", X_train.shape, # "Val:", X_val.shape,
      "Test:", X_test.shape)

del df_train, df_test # df_val
del train_table, test_table # val_table
del train_batches, test_batches #val_batches

n_features = X_train.shape[1]

# X_train_cnn = X_train.reshape(-1, n_features, 1)
# X_test_cnn  = X_test.reshape(-1, n_features, 1)

# num_classes = len(np.unique(y_train))
num_classes = 13
print("n_features:", n_features, "num_classes:", num_classes)
# print("X_train_cnn shape:", X_train_cnn.shape)

import tensorflow as tf
from tensorflow.keras import layers, models

tf.keras.backend.clear_session()

model = models.Sequential([
    layers.Input(shape=(n_features,)),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(num_classes, activation='softmax')  # 0–19 labels
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',  # because y is int labels
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train, y_train,
    epochs=8,          # start small; tune later
    batch_size=256,
    validation_split=0.1275,
    verbose=1
)

test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test loss: {test_loss:.4f}")
print(f"Test accuracy: {test_acc:.4f}")

from sklearn.metrics import confusion_matrix, classification_report

y_pred_probs = model.predict(X_test)
y_pred = y_pred_probs.argmax(axis=1)

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Make predictions on the test set
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)

# Generate the confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=np.arange(num_classes))

# Plot the confusion matrix
fig, ax = plt.subplots(figsize=(10, 10))
sns.heatmap(cm, annot=False, cmap='Blues', fmt='d', ax=ax)
ax.set_xlabel('Predicted Label')
ax.set_ylabel('True Label')
ax.set_title('Confusion Matrix')
plt.show()

cm_norm = confusion_matrix(y_test, y_pred, normalize='true')

plt.figure(figsize=(10,8))
sns.heatmap(cm_norm, annot=False, cmap="Blues")
plt.title("Normalized Confusion Matrix")
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.show()





import joblib
import os

# Define the path to save the model
model_path = os.path.join(shared_drive_path, "models", "cnn_model.joblib")

# Save the model
joblib.dump(model, model_path)

print(f"Model saved successfully to: {model_path}")