# -*- coding: utf-8 -*-
"""cnn_model_map2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4KW-4m8M23vF93r273grhnM52qegDye
"""

import os
from google.colab import drive
drive.mount('/content/drive')

shared_drive_name = "Sonoma Landcover Classification Project"

shared_drive_path = f"/content/drive/Shared drives/{shared_drive_name}"

subdirs = [
    "data/raw",
    "data/processed",
    "notebooks",
    "models",
    "exports",
    "figures"
]

for sub in subdirs:
    path = os.path.join(shared_drive_path, sub)
    os.makedirs(path, exist_ok=True)

print(f"Project directories ready under:\n{shared_drive_path}")
!ls -R "$shared_drive_path"

# Required for Colab
!pip -q install earthengine-api geemap

import ee, geemap
ee.Authenticate()
ee.Initialize(project='sonoma-lcc')

import joblib
import pandas as pd

model = joblib.load("/content/drive/Shared drives/Sonoma Landcover Classification Project/models/cnn_model.joblib")  # your trained cnn
feature_cols = ['A00', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19',
                'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30', 'A31', 'A32', 'A33', 'A34', 'A35', 'A36', 'A37', 'A38', 'A39',
                'A40', 'A41', 'A42', 'A43', 'A44', 'A45', 'A46', 'A47', 'A48', 'A49', 'A50', 'A51', 'A52', 'A53', 'A54', 'A55', 'A56', 'A57', 'A58', 'A59',
                'A60', 'A61', 'A62', 'A63']

import pyarrow.dataset as ds
import numpy as np
import pandas as pd

dataset_path = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_sonoma10m_2024_emb_only"
dataset = ds.dataset(dataset_path, format="parquet")

# Get fragments (which usually correspond to individual parquet files)
fragments = list(dataset.get_fragments())

dfs_pred = []

for fragment in fragments:
    # Load the entire fragment into a pandas DataFrame
    df_fragment = fragment.to_table().to_pandas()

    # Determine the number of rows to process (approximately half)
    half_rows = len(df_fragment) // 4

    # Select a random half of the rows from the fragment
    df_to_process = df_fragment.sample(half_rows, random_state=42) # Added random_state for reproducibility

    X = df_to_process[feature_cols].values
    y_pred = model.predict(X)

    # Get the class with the highest probability
    df_to_process['pred_label'] = np.argmax(y_pred, axis=1)
    dfs_pred.append(df_to_process)

df_pred_all = pd.concat(dfs_pred, ignore_index=True)

del dataset, fragments, df_fragment, df_to_process, X, y_pred

import geopandas as gpd
from shapely.geometry import Point

# optional: sample for plotting so you don’t try to draw millions of markers
df_plot = df_pred_all.sample(100_000, random_state=42)  # adjust or remove

geometry = [Point(xy) for xy in zip(df_plot['lon'], df_plot['lat'])]
gdf = gpd.GeoDataFrame(df_plot, geometry=geometry, crs="EPSG:4326")

import folium

# Center on Sonoma roughly
m = folium.Map(location=[38.4, -122.9], zoom_start=9)

# Simple palette per class
import matplotlib.cm as cm
import matplotlib.colors as colors

num_classes = gdf['pred_label'].nunique()
norm = colors.Normalize(vmin=gdf['pred_label'].min(), vmax=gdf['pred_label'].max())
cmap = cm.get_cmap('tab20', num_classes)

def color_for_label(lbl):
    r, g, b, _ = cmap(norm(lbl))
    return f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"

for _, row in gdf.iterrows():
    folium.CircleMarker(
        location=(row.geometry.y, row.geometry.x),
        radius=2,
        fill=True,
        fill_opacity=0.7,
        stroke=False,
        color=color_for_label(row['pred_label'])
    ).add_to(m)

# Define the custom label map
label_map_custom = {
    0: 'Unclassified',
    1: 'Annual Cropland',
    2: 'Barren & Sparsely Vegetated',
    3: 'Developed',
    4: 'Herbaceous',
    5: 'Intensively Managed Hayfield',
    6: 'Irrigated Pasture',
    7: 'Native Forest',
    8: 'Non-native Forest & Woodland',
    9: 'Orchard / Grove',
    10: 'Shrub',
    11: 'Vineyard',
    12: 'Water'
}

# Create a self-contained legend
legend_html = '''
<div style="position: fixed;
            bottom: 50px; left: 50px; width: 220px; height: auto;
            border:2px solid grey; z-index:9999; font-size:14px;
            background-color:white;
            opacity:0.9;
            ">
  &nbsp; <b>Predicted Land Cover</b> <br>
'''

unique_pred_labels = sorted(gdf['pred_label'].unique())

for label_val in unique_pred_labels:
    color = color_for_label(label_val) # Reuse the color_for_label function
    label_name = label_map_custom.get(label_val, f"Label {label_val}") # Get descriptive name
    legend_html += f'''
    &nbsp; <i style="background:{color}; width: 10px; height: 10px; float: left; margin-right: 8px;"></i>&nbsp; {label_name} <br>
    '''

legend_html += '''
</div>
'''

m.get_root().html.add_child(folium.Element(legend_html))

m



import folium
import geopandas as gpd
import matplotlib.cm as cm
import matplotlib.colors as colors
import os

# Center on Sonoma roughly
m = folium.Map(location=[38.4, -122.9], zoom_start=9)

# Load Sonoma County boundary (assuming Lifeform_5_1.shp is the boundary)
shared_drive_name = "Sonoma Landcover Classification Project"
shared_drive_path = f"/content/drive/Shared drives/{shared_drive_name}"
sonoma_boundary_path = os.path.join(shared_drive_path, 'data', 'raw', 'Lifeform_5_1.shp')
sonoma_boundary = gpd.read_file(sonoma_boundary_path)

# Ensure both GeoDataFrames have the same CRS
sonoma_boundary = sonoma_boundary.to_crs(gdf.crs)

# Perform a spatial join/filter to get points within Sonoma County
gdf_sonoma = gdf[gdf.within(sonoma_boundary.unary_union)]

num_classes = gdf_sonoma['pred_label'].nunique() # Use filtered gdf for class count
norm = colors.Normalize(vmin=gdf_sonoma['pred_label'].min(), vmax=gdf_sonoma['pred_label'].max())
cmap = cm.get_cmap('tab20', num_classes)

def color_for_label(lbl):
    r, g, b, _ = cmap(norm(lbl))
    return f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"

for _, row in gdf_sonoma.iterrows(): # Iterate over filtered gdf
    folium.CircleMarker(
        location=(row.geometry.y, row.geometry.x),
        radius=2,
        fill=True,
        fill_opacity=0.7,
        stroke=False,
        color=color_for_label(row['pred_label'])
    ).add_to(m)

# Define the custom label map
label_map_custom = {
    0: 'Unclassified',
    1: 'Annual Cropland',
    2: 'Barren & Sparsely Vegetated',
    3: 'Developed',
    4: 'Herbaceous',
    5: 'Intensively Managed Hayfield',
    6: 'Irrigated Pasture',
    7: 'Native Forest',
    8: 'Non-native Forest & Woodland',
    9: 'Orchard / Grove',
    10: 'Shrub',
    11: 'Vineyard',
    12: 'Water'
}

# Create a self-contained legend
legend_html = '''
<div style="position: fixed;
            bottom: 50px; left: 50px; width: 220px; height: auto;
            border:2px solid grey; z-index:9999; font-size:14px;
            background-color:white;
            opacity:0.9;
            ">
  &nbsp; <b>Predicted Land Cover</b> <br>
'''

unique_pred_labels = sorted(gdf_sonoma['pred_label'].unique()) # Use filtered gdf for legend labels

for label_val in unique_pred_labels:
    color = color_for_label(label_val) # Reuse the color_for_label function
    label_name = label_map_custom.get(label_val, f"Label {label_val}") # Get descriptive name
    legend_html += f'''
    &nbsp; <i style="background:{color}; width: 10px; height: 10px; float: left; margin-right: 8px;"></i>&nbsp; {label_name} <br>
    '''

legend_html += '''
</div>
'''

m.get_root().html.add_child(folium.Element(legend_html))

# Add the Sonoma County boundary to the map for visualization
folium.GeoJson(sonoma_boundary.__geo_interface__, style_function=lambda x: {'fillColor': '#00000000', 'color': 'red', 'weight': 2}).add_to(m)

m