# -*- coding: utf-8 -*-
"""rf_model_map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vwy0_tOYneeOEnFN2n4ybdKl_sD6vFd
"""

import os
from google.colab import drive
drive.mount('/content/drive')

shared_drive_name = "Sonoma Landcover Classification Project"

shared_drive_path = f"/content/drive/Shared drives/{shared_drive_name}"

subdirs = [
    "data/raw",
    "data/processed",
    "notebooks",
    "models",
    "exports",
    "figures"
]

for sub in subdirs:
    path = os.path.join(shared_drive_path, sub)
    os.makedirs(path, exist_ok=True)

print(f"Project directories ready under:\n{shared_drive_path}")
!ls -R "$shared_drive_path"

# Required for Colab
!pip -q install earthengine-api geemap

import ee, geemap
ee.Authenticate()
ee.Initialize(project='sonoma-lcc')

import joblib
import pandas as pd

rf = joblib.load("/content/drive/Shared drives/Sonoma Landcover Classification Project/models/random_forest_model.joblib")  # your trained RandomForest
feature_cols = ['A00', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19',
                'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30', 'A31', 'A32', 'A33', 'A34', 'A35', 'A36', 'A37', 'A38', 'A39',
                'A40', 'A41', 'A42', 'A43', 'A44', 'A45', 'A46', 'A47', 'A48', 'A49', 'A50', 'A51', 'A52', 'A53', 'A54', 'A55', 'A56', 'A57', 'A58', 'A59',
                'A60', 'A61', 'A62', 'A63']

import pyarrow.dataset as ds

dataset = ds.dataset("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_labels_1-12", format="parquet")

dfs_pred = []
for batch in dataset.to_batches():
    df = batch.to_pandas()

    X = df[feature_cols].values
    y_pred = rf.predict(X)

    df['pred_label'] = y_pred
    dfs_pred.append(df)

df_pred_all = pd.concat(dfs_pred, ignore_index=True)

import geopandas as gpd
from shapely.geometry import Point

# optional: sample for plotting so you don’t try to draw millions of markers
df_plot = df_pred_all.sample(100_000, random_state=42)  # adjust or remove

geometry = [Point(xy) for xy in zip(df_plot['lon'], df_plot['lat'])]
gdf = gpd.GeoDataFrame(df_plot, geometry=geometry, crs="EPSG:4326")

import folium

# Center on Sonoma roughly
m = folium.Map(location=[38.4, -122.9], zoom_start=9)

# Simple palette per class
import matplotlib.cm as cm
import matplotlib.colors as colors

num_classes = gdf['pred_label'].nunique()
norm = colors.Normalize(vmin=gdf['pred_label'].min(), vmax=gdf['pred_label'].max())
cmap = cm.get_cmap('tab20', num_classes)

def color_for_label(lbl):
    r, g, b, _ = cmap(norm(lbl))
    return f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"

for _, row in gdf.iterrows():
    folium.CircleMarker(
        location=(row.geometry.y, row.geometry.x),
        radius=2,
        fill=True,
        fill_opacity=0.7,
        stroke=False,
        color=color_for_label(row['pred_label'])
    ).add_to(m)

m





import pyarrow.dataset as ds

dataset = ds.dataset("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_labels_1-12/tile_38.parquet")

dfs_pred = []
for batch in dataset.to_batches():
    df = batch.to_pandas()

    X = df[feature_cols].values
    y_pred = rf.predict(X)

    df['pred_label'] = y_pred
    dfs_pred.append(df)

df_pred_all = pd.concat(dfs_pred, ignore_index=True)

import geopandas as gpd
from shapely.geometry import Point

# optional: sample for plotting so you don’t try to draw millions of markers
df_plot = df_pred_all.sample(100_000, random_state=42)  # adjust or remove

geometry = [Point(xy) for xy in zip(df_plot['lon'], df_plot['lat'])]
gdf = gpd.GeoDataFrame(df_plot, geometry=geometry, crs="EPSG:4326")

import folium

# Center on Sonoma roughly
m = folium.Map(location=[38.4, -122.9], zoom_start=9)

# Simple palette per class
import matplotlib.cm as cm
import matplotlib.colors as colors

num_classes = gdf['pred_label'].nunique()
norm = colors.Normalize(vmin=gdf['pred_label'].min(), vmax=gdf['pred_label'].max())
cmap = cm.get_cmap('tab20', num_classes)

def color_for_label(lbl):
    r, g, b, _ = cmap(norm(lbl))
    return f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"

for _, row in gdf.iterrows():
    folium.CircleMarker(
        location=(row.geometry.y, row.geometry.x),
        radius=2,
        fill=True,
        fill_opacity=0.7,
        stroke=False,
        color=color_for_label(row['pred_label'])
    ).add_to(m)

m