# -*- coding: utf-8 -*-
"""XGBoostTest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haSlMnnm-28TRmWZ8_hyPDP8unlTfmCj
"""

import os
from google.colab import drive
drive.mount('/content/drive')

shared_drive_name = "Sonoma Landcover Classification Project"

shared_drive_path = f"/content/drive/Shared drives/{shared_drive_name}"

subdirs = [
    "data/raw",
    "data/processed",
    "data/processed/DataFrames",
    "notebooks",
    "models",
    "exports",
    "figures"
]

for sub in subdirs:
    path = os.path.join(shared_drive_path, sub)
    os.makedirs(path, exist_ok=True)

print(f"Project directories ready under:\n{shared_drive_path}")
!ls -R "$shared_drive_path"

import ee

ee.Authenticate()
ee.Initialize(project='sonoma-lcc')

!pip -q install rasterio pyarrow pyproj tqdm

import os
import geopandas as gpd, rasterio
import pandas as pd
import numpy as np
from shapely.validation import make_valid
import rasterio
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import folium
from tqdm import tqdm
import geopandas as gpd
from shapely.geometry import box
import datetime as dt
from tqdm.auto import tqdm, trange
import time
import re
from pathlib import Path
from rasterio.warp import reproject
from rasterio.enums import Resampling as RS
import pyarrow as pa, pyarrow.parquet as pq
from pyproj import Transformer, CRS

!pip install pyarrow pandas

import pyarrow.parquet as pq
import pyarrow.dataset as ds
import pyarrow as pa
import pandas as pd
import glob, os

!pip -q install xgboost

from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

dataset = ds.dataset("/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_labels_1-12", format="parquet")

feature_cols = ['A00', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19',
                'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30', 'A31', 'A32', 'A33', 'A34', 'A35', 'A36', 'A37', 'A38', 'A39',
                'A40', 'A41', 'A42', 'A43', 'A44', 'A45', 'A46', 'A47', 'A48', 'A49', 'A50', 'A51', 'A52', 'A53', 'A54', 'A55', 'A56', 'A57', 'A58', 'A59',
                'A60', 'A61', 'A62', 'A63']
label_col = 'label'
needed_cols = feature_cols + [label_col]

#v2
import hashlib
import pyarrow.compute as pc

root = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_labels_1-12"
dataset = ds.dataset(root, format="parquet")

feature_cols = [f"A{str(i).zfill(2)}" for i in range(64)]
label_col = "label"
needed_cols = feature_cols + [label_col]

def tile_split(path, train=0.70, val=0.15):
    # deterministic split per file name
    name = os.path.basename(path)
    h = int(hashlib.md5(name.encode()).hexdigest(), 16) % 100000 / 100000.0
    if h < train:
        return "train"
    elif h < train + val:
        return "val"
    else:
        return "test"

train_batches, val_batches, test_batches = [], [], []

for frag in dataset.get_fragments():
    split = tile_split(frag.path)
    for batch in frag.to_batches(columns=needed_cols):
        # keep your usual label filtering (recommended)
        mask = pc.not_equal(batch[label_col], 0)
        batch = batch.filter(mask)

        if split == "train":
            train_batches.append(batch)
        elif split == "val":
            val_batches.append(batch)
        else:
            test_batches.append(batch)

train_table = pa.Table.from_batches(train_batches)
val_table   = pa.Table.from_batches(val_batches)
test_table  = pa.Table.from_batches(test_batches)

df_train = train_table.to_pandas()
df_val   = val_table.to_pandas()
df_test  = test_table.to_pandas()

X_train = df_train[feature_cols].to_numpy(np.float32)
y_train = df_train[label_col].to_numpy(np.int32)
X_val   = df_val[feature_cols].to_numpy(np.float32)
y_val   = df_val[label_col].to_numpy(np.int32)
X_test  = df_test[feature_cols].to_numpy(np.float32)
y_test  = df_test[label_col].to_numpy(np.int32)

print(X_train.shape, X_val.shape, X_test.shape)

# Train set
X_train = df_train[feature_cols].to_numpy(dtype=np.float32)
y_train = df_train['label'].to_numpy(dtype=np.int32)

# Validation set
X_val   = df_val[feature_cols].to_numpy(dtype=np.float32)
y_val   = df_val['label'].to_numpy(dtype=np.int32)

# Test set
X_test  = df_test[feature_cols].to_numpy(dtype=np.float32)
y_test  = df_test['label'].to_numpy(dtype=np.int32)

print("Train shape:", X_train.shape, "Val:", X_val.shape, "Test:", X_test.shape)

le = LabelEncoder()

y_train_enc = le.fit_transform(y_train)
y_val_enc   = le.transform(y_val)
y_test_enc  = le.transform(y_test)

num_classes = len(le.classes_)
print("Classes:", le.classes_, "num_classes:", num_classes)

del df_train, df_val, df_test
del train_table, val_table, test_table
del train_batches, val_batches, test_batches

!pip -q install -U cupy-cuda12x

import cupy as cp

!pip -q install -U xgboost

import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

print("xgboost version:", xgb.__version__)

# Encode labels to 0..K-1
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_val_enc   = le.transform(y_val)
y_test_enc  = le.transform(y_test)
num_classes = len(le.classes_)

# GPU in Colab: tree_method='hist' + device='cuda'
use_gpu = True

xgb_clf = XGBClassifier(
    objective="multi:softprob",
    num_class=num_classes,
    tree_method="hist",
    device="cuda" if use_gpu else "cpu",

    # core params
    max_depth=10,
    learning_rate=0.1,
    n_estimators=4000,          # let early stopping decide
    subsample=0.8,
    colsample_bytree=0.8,
    reg_lambda=1.0,
    min_child_weight=1,

    eval_metric="mlogloss",

    # early stopping HERE
    early_stopping_rounds=50,

    n_jobs=-1,
    random_state=42
)

xgb_clf.fit(
    X_train, y_train_enc,
    eval_set=[(X_val, y_val_enc)],
    verbose=50
)

X_val_gpu  = cp.asarray(X_val)
X_test_gpu = cp.asarray(X_test)

val_pred_enc  = xgb_clf.predict(X_val_gpu)
test_pred_enc = xgb_clf.predict(X_test_gpu)

val_pred_enc  = cp.asnumpy(val_pred_enc)
test_pred_enc = cp.asnumpy(test_pred_enc)

print("Validation accuracy:", accuracy_score(y_val_enc, val_pred_enc))
print("Test accuracy:", accuracy_score(y_test_enc, test_pred_enc))

y_test_pred = le.inverse_transform(test_pred_enc)
print("\nClassification report (test):\n", classification_report(y_test, y_test_pred))

train_pred = xgb_clf.predict(cp.asarray(X_train))
train_pred = cp.asnumpy(train_pred)
print("Train accuracy:", (train_pred == y_train_enc).mean())
print("Val accuracy:",   (val_pred_enc == y_val_enc).mean())
print("Test accuracy:",  (test_pred_enc == y_test_enc).mean())

# if you have cell_id in each df before deleting:
train_ids = set(zip(df_train["cell_id"].values))
val_ids   = set(zip(df_val["cell_id"].values))
test_ids  = set(zip(df_test["cell_id"].values))

print("train∩val:", len(train_ids & val_ids))
print("train∩test:", len(train_ids & test_ids))
print("val∩test:", len(val_ids & test_ids))

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_test_pred)
disp = ConfusionMatrixDisplay(cm)
disp.plot(xticks_rotation='vertical')
plt.show()

from sklearn.metrics import accuracy_score, classification_report

y_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import ConfusionMatrixDisplay

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(xticks_rotation='vertical', cmap='Blues')

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.title("Confusion Matrix")
plt.show()

cm_norm = confusion_matrix(y_test, y_pred, normalize='true')

plt.figure(figsize=(10,8))
sns.heatmap(cm_norm, annot=False, cmap="Blues")
plt.title("Normalized Confusion Matrix")
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.show()

normalized_cm_all = confusion_matrix(y_test, y_pred, normalize='all')
#normalized_cm_pred = confusion_matrix(y_test, y_pred, normalize='pred')
#normalized_cm_true = confusion_matrix(y_test, y_pred, normalize='true')

pathway = "/content/drive/Shared drives/Sonoma Landcover Classification Project/data/processed/parquet_labels_1-12/tile_39.parquet"

df = pd.read_parquet(pathway)
X_parquet_test  = df[feature_cols].to_numpy(dtype=np.float32)
y_parquet_test  = df['label'].to_numpy(dtype=np.int32)

y_test_pred = rf.predict(X_parquet_test)

print("Test accuracy:", accuracy_score(y_parquet_test, y_test_pred))
print("\nClassification report (test):\n", classification_report(y_parquet_test, y_test_pred))

import joblib
import os

# Define the path to save the model
model_path = os.path.join(shared_drive_path, "models", "rf2_model.joblib")

# Save the model
joblib.dump(rf, model_path)

print(f"Model saved successfully to: {model_path}")